### ISSUE TITLE
Improvment on OCR ability?

### ISSUE THREAD

**Issue by lucasjinreal** [OpenBMB/MiniCPM#10]
After testd, the vision model are really weak at OCR ability. By saying OCR, means understand images contains characters, but this vision model lack of it.

Any idea to improve it?

**Comment by yaoyuanTHU** [comment]
Hi, thanks for the feedback! We currently removed this part in the introduction of OmniLMM. Stronger OCR capability is on the way. This could be achieved by learning more from OCR supervision during pretraining. Thanks!

**Comment by lucasjinreal** [comment]
@yaoyuanTHU  Please pin me if new ocr calability improved!
