### ISSUE TITLE
How to get a smaller language model counterpart

### ISSUE THREAD

**Issue by JiwenJ** [OpenBMB/MiniCPM#100]
Sorry to bother, I wonder how to get a smaller language model like 0.009B model. Is it to modify the num_layer or d_model or both, I really appreciate it if you can help with that problem.

**Comment by zRzRzRzRzRzRzR** [comment]
To reach a model size of approximately 0.009B parameters (pretrain by yourself), you'll need to experiment with these parameters. A significant reduction in both the number of layers and the hidden size is necessary. You might start with reducing num_hidden_layers to a much lower number (like 4-6) and hidden_size to around 256-512. The number of attention heads may also need to be reduced proportionally.
