### ISSUE TITLE
MiniCPM-V 微调(finetune)代码的支持

### ISSUE THREAD

**Issue by Jintao-Huang** [OpenBMB/MiniCPM#103]
大模型微调框架swift已经支持啦minicpm-v的微调. 😊

最佳实践可以查看这里：https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/minicpm-v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md

**Comment by LDLINGLINGLING** [comment]
感谢您的贡献。
