### ISSUE TITLE
[Bug]:     assert rx.analysis.well_formed(mod) AssertionError

### ISSUE THREAD

**Issue by Chowhound-G** [OpenBMB/MiniCPM#104]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

```
MODEL_NAME=MiniCPM
QUANTIZATION=q4f16_1
MODEL_TYPE=minicpm
mlc_chat convert_weight --model-type ${MODEL_TYPE} ./dist/models/${MODEL_NAME}-hf/ --quantization $QUANTIZATION -o dist/$MODEL_NAME/
mlc_chat gen_config --model-type ${MODEL_TYPE} ./dist/models/${MODEL_NAME}-hf/ --quantization $QUANTIZATION --conv-template LM --sliding-window-size 768 -o dist/${MODEL_NAME}/
mlc_chat compile --model-type ${MODEL_TYPE} dist/${MODEL_NAME}/mlc-chat-config.json --device android -o ./dist/libs/${MODEL_NAME}-android.tar
cd ./android/library
./prepare_libs.sh
cd -
```

Error:
/tvm/relax/frontend/nn/exporter.py", line 139, in build
    assert rx.analysis.well_formed(mod)
AssertionError

### To Reproduce / 如何复现

while running this:
`mlc_chat convert_weight --model-type ${MODEL_TYPE} ./dist/models/${MODEL_NAME}-hf/ --quantization $QUANTIZATION -o dist/$MODEL_NAME/`

### Expected behavior / 期望的结果

mlc_chat convert_weight --model-type ${MODEL_TYPE} ./dist/models/${MODEL_NAME}-hf/ --quantization $QUANTIZATION -o dist/$MODEL_NAME/

### Screenshots / 截图

<img width="1512" alt="截屏2024-03-20 12 59 19" src="https://github.com/OpenBMB/MiniCPM/assets/95733444/69fb558f-eb15-45b8-b25f-9cc17a16c5db">

### Environment / 环境

```shell
- OS: [MaCOS 14.4]
```

### Additional context / 其他信息

A same error exist:
https://github.com/mlc-ai/mlc-llm/issues/1944

That shows an update from mlc_chat to mlc_llm

<img width="1179" alt="截屏2024-03-20 13 04 01" src="https://github.com/OpenBMB/MiniCPM/assets/95733444/44de50e1-ff1e-4ea4-9308-1be93ccd2231">

**Comment by Achazwl** [comment]
We find that
`mlc_ai_nightly-0.15.dev228-cp39-cp39-macosx_13_0_arm64.whl`
can reproduce your issue while
`mlc_ai-0.15.1-cp39-cp39-macosx_13_0_arm64.whl`
can solve your issue.

That is, install the version without nightly in [https://mlc.ai/wheels](https://mlc.ai/wheels).
