### ISSUE TITLE
平板可以部署吗？平板性能比一般的手机要强吧[Feature Request]: 

### ISSUE THREAD

**Issue by zhjygit** [OpenBMB/MiniCPM#108]
### Feature request  / 功能建议

手机端用的是安卓系统，apk默认下载的是int4量化模型，2.5tok/s对话能力；如果平板端安卓系统，性能会不会更强一点。平板端不用int4量化的话可以吗？端侧部署能力对硬件需求是什么？如果要平板部署，不适用int4量化，应该怎么部署呀，现在的apk会默认下载int4量化模型，如果不想要int4量化模型，需要手动编译吗？

**Comment by jctime** [comment]
平板安卓上跑，和手机差不多，性能主要依赖cpu芯片和内存，越大速度越快。apk默认int是为了对手机内存的友好，不想的话可以自己编译一个，参考相关教程就行。
