### ISSUE TITLE
[Bad Case]: 添加finetune后的模型转换

### ISSUE THREAD

**Issue by R0k1e** [OpenBMB/MiniCPM#109]
### Description / 描述

使用sft_finentune.sh之后生成的ckpt无法直接使用inference处的模型转换，不存在pytorch_model.bin导致无法直接加载，不存在tokenizer.model导致无法直接复制。同时根据 #9 配置的transformers版本无法直接使用AutoModel，需要至少将transformers版本升级为4.36。

**Comment by LDLINGLINGLING** [comment]
感谢您的反馈，可以尝试升级transformer或者修改代码保存为pytorch_model.bin
