### ISSUE TITLE
[Feature Request]: README中的不严谨处

### ISSUE THREAD

**Issue by Lukeehoojet** [OpenBMB/MiniCPM#11]
### Feature request  / 功能建议

项目在README中宣称`MiniCPM-V 也首次跑通了多模态大模型在手机上的部署`可能不太严谨.

- [llama.cpp](https://github.com/ggerganov/llama.cpp#:~:text=GPT%2D2-,Multimodal%20models%3A,-Llava%201.5%20models)项目已经支持LLaVA 1.5和MobileVLM等多模态模型,并可以编译到adb命令行运行. 

- 今年早些时候发布的[mllm](https://github.com/UbiquitousLearning/mllm)框架也支持在Android端运行多模态模型,并给出了Demo App.

**Comment by ShengdingHu** [comment]
已修改，感谢指出我们的调研不充分之处! 
Amended, thank you for pointing out the inadequacies in our research!

**Comment by ShengdingHu** [comment]
我们确认我们是国内首家这样做的公司，所以你可能会看到一些使用类似词的宣传稿。
We confirmed that we are the first in China to do this, so you may see some promotional material taking this term.

**Comment by ShengdingHu** [comment]
Sorry again for the confusion we've made.
