### ISSUE TITLE
那个版本的vllm支持2b-dpo-bf16啊

### ISSUE THREAD

**Issue by Liyu910228** [OpenBMB/MiniCPM#113]
<img width="809" alt="1711968124424" src="https://github.com/OpenBMB/MiniCPM/assets/55588842/5fd5f15f-6c8d-4ca0-b9e2-239c8a5d8121">

<img width="814" alt="1711968052889" src="https://github.com/OpenBMB/MiniCPM/assets/55588842/145f45ef-94d2-4cde-828b-198452a46e01">

安装好几个版本vllm都不支持，哪位大佬看看

**Comment by zRzRzRzRzRzRzR** [comment]
应该是要用这个仓库里指定的吧，因为vllm没有注册minicpm？

**Comment by zh-zheng** [comment]
vllm [v0.4.1](https://github.com/vllm-project/vllm/releases/tag/v0.4.1)已经支持了MiniCPM。
