### ISSUE TITLE
[Feature Request]: Readme should state MiniCPM does not support macOS

### ISSUE THREAD

**Issue by jazelly** [OpenBMB/MiniCPM#12]
### Feature request  / 功能建议

Hi, I was trying to get this up running on my macOS, and found [this](https://github.com/facebookresearch/xformers/issues/828).
Since there is a dependency to `xformers`, I think MiniCPM cannot support macOS as well?

**Comment by SUDA-HLT-ywfang** [comment]
Hi, 
there are some bugs now when running on cpu machines. We are working on it, please stay tuned.

**Comment by zkh2016** [comment]
Hello @jazelly, Running minicpm on Mac can use [LLMFarm-MiniCPM](https://github.com/OpenBMB/LLMFarm-MiniCPM).

**Comment by huangyuxiang03** [comment]
Hi, we have fixed the bug that MiniCPM cannot run on macOS. For current version, please install cpu version (or mps version) torch and run MiniCPM with float32 precision on cpu, using huggingface transformers. MiniCPM can run on Mac without xformers.
