### ISSUE TITLE
想问一下“大部分非专有数据”的预期开放时间和数量级

### ISSUE THREAD

**Issue by berton820** [OpenBMB/MiniCPM#123]
我们将完全开源MiniCPM-2B的模型参数供学术研究和有限商用，以及训练过程中的所有Checkpoint和大部分非专有数据(需要一定时间准备）给模型机理研究。

来源
https://shengdinghu.notion.site/MiniCPM-c805a17c5c8046398914e47f0542095a

**Comment by jctime** [comment]
数据还在处理准备中，敬请期待
