### ISSUE TITLE
基于MiniCPM-2B-sft-bf16进行sft，训练集loss下降到0.1，测试集loss上升到4.2

### ISSUE THREAD

**Issue by zr-icu** [OpenBMB/MiniCPM#125]
你好，感谢代码的分享！
使用MiniCPM-2B-sft-bf16 在下游数据集进行训练，分布是一致的数据，使用sft_fintune.sh 进行训练，训练集loss 逐渐降低从2.多下降到0.1，但是测试集的loss从2.多上升到4.多。使用中间保存的节点进行推理，推理出来的内容完全不相关，请问可能是哪里有问题咧？

**Comment by zRzRzRzRzRzRzR** [comment]
这个感觉是过拟合了吧？毕竟模型比较小？我在其他大一点的模型微调好像没有出现这个问题

**Comment by zr-icu** [comment]
> 这个感觉是过拟合了吧？毕竟模型比较小？我在其他大一点的模型微调好像没有出现这个问题

好的，那我调整一下参数试下。。 这个问题确实一直没考虑过 0.0 之前在其他大语言模型训练确实没出现过，就没往这个方向考虑，我试一下，感谢回复

**Comment by cheesewafer** [comment]
遇到同样的问题，请问解决了吗

> > 这个感觉是过拟合了吧？毕竟模型比较小？我在其他大一点的模型微调好像没有出现这个问题
> 
> 好的，那我调整一下参数试下。。 这个问题确实一直没考虑过 0.0 之前在其他大语言模型训练确实没出现过，就没往这个方向考虑，我试一下，感谢回复
