### ISSUE TITLE
[Feature Request]: Running multimodal on llama.cpp?

### ISSUE THREAD

**Issue by yyyoungman** [OpenBMB/MiniCPM#129]
### Feature request  / 功能建议

Seems only the text part is supported on llama.cpp, but the multimodal part is not. It would be really helpful if it could be supported, because llama.cpp is so widely used now (much more use than mlc) and easy to deploy on edge devices. Would also greatly improve the impact of this work. Thanks!

**Comment by LDLINGLINGLING** [comment]
We forked the code of llama.cpp: 
https://github.com/OpenBMB/llama.cpp/tree/minicpm-v2.5/examples/minicpmv
Here you can learn how to use llama.cpp to use our multi-moda, Hope this is useful to you
