### ISSUE TITLE
[Feature Request]:ollama怎么部署新版v2 

### ISSUE THREAD

**Issue by yuanjie-ai** [OpenBMB/MiniCPM#133]
### Feature request  / 功能建议

ollama怎么部署新版v2

**Comment by zkh2016** [comment]
ollama依赖llama.cpp，这个我们已经支持，但是代码还没合入主干，如果着急使用可以先拉这个[PR](https://github.com/ggerganov/llama.cpp/pull/6919)

**Comment by yuanjie-ai** [comment]
```json
{
  "error": {
    "message": "json: cannot unmarshal array into Go struct field Message.messages.content of type string (request id: 202405201737573290654078XyZdsli)",
    "type": "invalid_request_error",
    "param": "",
    "code": null
  }
}
```
报错ollama run modelbest/minicpm-2b-dpo

**Comment by LDLINGLINGLING** [comment]
https://github.com/LDLINGLINGLING/MiniCPM/tree/ollama_manual_installation
去以上链接寻找ollama的本地部署方法，以上仍未并入我方main
