### ISSUE TITLE
[Bug]: How to train from scratch？

### ISSUE THREAD

**Issue by sankexin** [OpenBMB/MiniCPM#136]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

it is a good project! but , How to train from scratch？When can we git code for scratch train?

### To Reproduce / 如何复现

How to train from scratch？

### Expected behavior / 期望的结果

How to train from scratch？

### Screenshots / 截图

How to train from scratch？

### Environment / 环境

```shell
How to train from scratch？
```

### Additional context / 其他信息

How to train from scratch？

**Comment by LDLINGLINGLING** [comment]
For this issue, you can pay attention to our papers, or take a look at projects such as nanogpt and so on.
