### ISSUE TITLE
[继续预训练的学习策略]

### ISSUE THREAD

**Issue by mynewstart** [OpenBMB/MiniCPM#137]
您好，
请问如果想在你们模型的基础上继续在某个领域的数据(大概20B）上继续预训练，是不是可以在你们退火后的学习率1e-3的基础上使用WSD的学习策略？是将1e-3设置为最大学习率，然后运用你们的公式根据步数调整LR吗？

**Comment by LDLINGLINGLING** [comment]
个人认为应该在官网找到stable阶段最后的checkpints，然后考虑WSD的持续训练和退火训练。
