### ISSUE TITLE
[Bad Case]: ollama部署效果比较差

### ISSUE THREAD

**Issue by ljch2018** [OpenBMB/MiniCPM#139]
### Description / 描述

<img width="1001" alt="infoflow 2024-05-24 11-31-39" src="https://github.com/OpenBMB/MiniCPM/assets/22562546/56d17efa-d737-416b-a2db-d20bf2ad54ce">

**Comment by ljch2018** [comment]
没有一个是对的啊。

**Comment by ljch2018** [comment]
<img width="1044" alt="image" src="https://github.com/OpenBMB/MiniCPM/assets/22562546/3a53cde8-a3da-4171-8ea2-7c74bb385391">

**Comment by LDLINGLINGLING** [comment]
确认了一下，这个问题确实存在，主要原因可能在于生成参数的问题：
TEMPLATE <用户>{{ .Prompt }}<AI>
PARAMETER temperature 0.3
PARAMETER top_p 0.8
PARAMETER frequency_penalty 0
PARAMETER num_ctx 8192
PARAMETER num_predict 20
PARAMETER presence_penalty 0
PARAMETER repeat_penalty 1
PARAMETER seed 42
以上参数重num_predict 20，导致以上生成总被截断。
https://github.com/LDLINGLINGLING/MiniCPM/tree/ollama_manual_installation
