### ISSUE TITLE
[Bug]: vllm 推理量化权重报错：KeyError: 'lm_head.weight'

### ISSUE THREAD

**Issue by lee0v0** [OpenBMB/MiniCPM#141]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

vllm推理量化版本的模型权重出现上述bug

### To Reproduce / 如何复现
```bash
python inference/inference_vllm.py --model_path openbmb/MiniCPM-2B-dpo-int4  --prompt_path prompt_demo.txt 
```

### Environment / 环境

```shell
- OS:  Ubuntu 20.04
- Pytorch:  2.3.0
- CUDA: cuda12.1
- Device: RTX4070
- vllm: 0.4.2
- weight: openbmb/MiniCPM-2B-dpo-int4
```

**Comment by LDLINGLINGLING** [comment]
git vllm 代码后，在vllm-main/vllm/model_executor/models/minicpm.py的第500行：
for name, loaded_weight in weights:下方插入以下代码
       if 'lm_head.weight' in name:
                continue
然后仔执行pip install e .便可解决
