### ISSUE TITLE
[Bad Case]: 代码生成能力存疑

### ISSUE THREAD

**Issue by Rundong-Li** [OpenBMB/MiniCPM#143]
### Description / 描述

使用demo中的prompt”编写一个python程序实现一个MiniCPM模型：Transformer结构，40层，每层的维度为2304，词表大小为112753“，在MiniCPM-2B-sft-fp32/MiniCPM-2B-dpo-bf16/MiniCPM-2B-sft-bf16上进行多次重复测试，代码生成效果非常差，经常会陷入死循环（重复固定的内容直至max_len，无法正常生成\<eos\>），我不太明白这是什么原因。我看到在HumanEval上，MiniCPM的得分显著高于其他开源模型，甚至比Qwen1.5-72B的分数还高（50 vs 41.5），但实际使用中并没有感受到强大的代码生成能力。
以下是一个例子：
<img width="692" alt="1" src="https://github.com/OpenBMB/MiniCPM/assets/48337831/3ba02785-cbc5-4722-b557-abcfde48c8df">
<img width="666" alt="2" src="https://github.com/OpenBMB/MiniCPM/assets/48337831/bf882215-122c-4d65-9dce-c59a33edda3a">
<img width="674" alt="3" src="https://github.com/OpenBMB/MiniCPM/assets/48337831/87443210-4a1d-421b-b560-d39eeecffe5f">

**Comment by LDLINGLINGLING** [comment]
User: 编写一个python程序实现一个MinicPM模型（Transformer结构，40层，每层的维度为2304，词表大小为112753)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
以下是一个使用Python和PyTorch实现的MinicPM模型的示例。这个模型使用了Transformer结构，共有40层，每层的维度为2304，词表大小为112753。

```python
import torch
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable

class MinicPM(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, num_layers, dropout_p):
        super(MinicPM, self).__init__()
        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers
        self.dropout_p = dropout_p

        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.transformer = nn.Transformer(embedding_dim, hidden_dim, num_layers, dropout_p)
        self.decoder = nn.Linear(hidden_dim, vocab_size)

    def forward(self, src, src_mask, src_key_padding_mask):
        embedded = self.embedding(src)
        output, _ = self.transformer(embedded, src_mask, src_key_padding_mask)
        output = self.decoder(output)
        return output

def main():
    vocab_size = 112753
    embedding_dim = 2304
    hidden_dim = 2304
    num_layers = 40
    dropout_p = 0.1

    model = MinicPM(vocab_size, embedding_dim, hidden_dim, num_layers, dropout_p)

    # 加载预训练的词向量
    embeddings = torch.load('pretrained_embeddings.pt')
    model.embedding.weight.data.copy_(embeddings)

    # 设置随机种子以保持一致性
    torch.manual_seed(42)

    # 示例输入数据
    input_text = "这是一个示例文本"
    input_tokens = [input_text]
    input_sequence = input_tokens

    # 生成输出
    output = model(input_sequence)
    print(output)

if __name__ == "__main__":
    main()
    
以上是我通过和你一样的prompt，minicpm2-2b-bf16输出的结果

**Comment by Rundong-Li** [comment]
> User: 编写一个python程序实现一个MinicPM模型（Transformer结构，40层，每层的维度为2304，词表大小为112753) Setting `pad_token_id` to `eos_token_id`:2 for open-end generation. 以下是一个使用Python和PyTorch实现的MinicPM模型的示例。这个模型使用了Transformer结构，共有40层，每层的维度为2304，词表大小为112753。
> 
> ```python
> import torch
> import torch.nn as nn
> import torch.optim as optim
> from torch.autograd import Variable
> 
> class MinicPM(nn.Module):
>     def __init__(self, vocab_size, embedding_dim, hidden_dim, num_layers, dropout_p):
>         super(MinicPM, self).__init__()
>         self.vocab_size = vocab_size
>         self.embedding_dim = embedding_dim
>         self.hidden_dim = hidden_dim
>         self.num_layers = num_layers
>         self.dropout_p = dropout_p
> 
>         self.embedding = nn.Embedding(vocab_size, embedding_dim)
>         self.transformer = nn.Transformer(embedding_dim, hidden_dim, num_layers, dropout_p)
>         self.decoder = nn.Linear(hidden_dim, vocab_size)
> 
>     def forward(self, src, src_mask, src_key_padding_mask):
>         embedded = self.embedding(src)
>         output, _ = self.transformer(embedded, src_mask, src_key_padding_mask)
>         output = self.decoder(output)
>         return output
> 
> def main():
>     vocab_size = 112753
>     embedding_dim = 2304
>     hidden_dim = 2304
>     num_layers = 40
>     dropout_p = 0.1
> 
>     model = MinicPM(vocab_size, embedding_dim, hidden_dim, num_layers, dropout_p)
> 
>     # 加载预训练的词向量
>     embeddings = torch.load('pretrained_embeddings.pt')
>     model.embedding.weight.data.copy_(embeddings)
> 
>     # 设置随机种子以保持一致性
>     torch.manual_seed(42)
> 
>     # 示例输入数据
>     input_text = "这是一个示例文本"
>     input_tokens = [input_text]
>     input_sequence = input_tokens
> 
>     # 生成输出
>     output = model(input_sequence)
>     print(output)
> 
> if __name__ == "__main__":
>     main()
>     
> 以上是我通过和你一样的prompt，minicpm2-2b-bf16输出的结果
> ```
这个生成的结果是基本正确的，但代码功能的完整程度还是不如这个例子
![image](https://github.com/OpenBMB/MiniCPM/assets/48337831/dd491b10-8e20-42d5-8666-ca14a6f6f62a)

**Comment by LDLINGLINGLING** [comment]
感谢您反馈，不同的生成参数确实会导致有不同的结果，不同的prompt也会有不同的效果。
