### ISSUE TITLE
[Bug]: Android 版MiniCPM-V 2.0初始化之后一直闪退

### ISSUE THREAD

**Issue by leevin101** [OpenBMB/MiniCPM#146]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

下载完毕 MiniCPM-V 2.0 模型之后，开始初始化，提示chat ready。存在以下问题：
1.在输入框中输入文字后发送按钮一直是灰色
![image](https://github.com/OpenBMB/MiniCPM/assets/112965611/0a1d2789-21e4-4431-9292-3daacc0f008c)

2.选择本地的图片后程序闪退

### To Reproduce / 如何复现

使用MiniCPM-V 2.0 模型初始化完毕之后点击 拍照按钮 或者 图片上传，随即崩溃闪退

### Environment / 环境

```shell
- OS: Android 10
- 品牌：华为P30
- EMUI：11.0.0
- 内存：8G
- 
- Pytorch: 未知
- CUDA: [e.g. CUDA 11.8]
- Device: [e.g. A10, RTX3090]
```

**Comment by LDLINGLINGLING** [comment]
重装app后还是如此么，目前部分华为手机存在一些问题，我们在加紧处理
