### ISSUE TITLE
No such file or directory: 'prompts/prompt_demo.txt'[Bad Case]: 

### ISSUE THREAD

**Issue by scalaboy** [OpenBMB/MiniCPM#147]
### Description / 描述

just run the vllm demo.get this erro:
python inference/inference_vllm.py --model_path MiniCPM --prompt_path prompts/prompt_demo.txt
the error log is :
No such file or directory: 'prompts/prompt_demo.txt'

**Comment by LDLINGLINGLING** [comment]
你可以自己新建一个prompts/prompt_demo.txt，每一行是一个prompt，也可以自己改 --prompt_path 后面的参数用以设置你的prompt文件路径
