### ISSUE TITLE
使用vllm推理模型，出现异常。

### ISSUE THREAD

**Issue by GromZhang** [OpenBMB/MiniCPM#158]
按照readme的指引，我下载了vllm，并按照
python inference/inference_vllm.py --model_path <hf_repo_path> --prompt_path prompts/prompt_demo.txt
进行推理，但是在执行的时候出现了如下异常
![image](https://github.com/OpenBMB/MiniCPM/assets/23513264/c1af9829-3090-4b03-8862-cd2ed0f9dc22)
其中vllm的版本是vllm==0.4.2，是从vllm官网上下载的docker镜像
请各位老师帮忙指导

**Comment by LDLINGLINGLING** [comment]
在llm=LLM(model=......,trust_remote_code=True)这一行，加入：
trust_remote_code=True试试

**Comment by GromZhang** [comment]
按照上面这位老师的指导，通过了用例

**Comment by LDLINGLINGLING** [comment]
能够帮到你就好
