### ISSUE TITLE
[Bad Case]: 为什么pip install -r requirements.txt会不停地进行安装 requirements.txt以外的包

### ISSUE THREAD

**Issue by Firestar117** [OpenBMB/MiniCPM#159]
### Description / 描述

为什么pip install -r requirements.txt会不停地进行安装 requirements.txt以外的包

**Comment by LDLINGLINGLING** [comment]
因为看不到您的pip安装包，我猜测是安装requrements中的某些包时，这些包本身就语言安装一些依赖包，因此导致了您所反馈的问题
