### ISSUE TITLE
[Bad Case]: 推理时间过长

### ISSUE THREAD

**Issue by jichaoqun** [OpenBMB/MiniCPM#163]
### Description / 描述

搭建环境后，使用推荐代码进行推理，在单张3090上得到的结果的时间过长，在8分钟以上。
请问有什么方法可以减少推理时间，还有，为什么会出现推理时间过长

**Comment by LDLINGLINGLING** [comment]
您好，能否吧推理代发出来看一下呢，并且统计一下输出长度，最好看一下是否在cpu上进行推理

**Comment by jichaoqun** [comment]
我的代码：
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import time

start_time = time.time()

torch.manual_seed(0)

#path = '/home/ps/disk4T/jcq/minicpm/models/minicpm-2b-128k'
path = '/home/student/disk4T/student/jcq/minicpm/models/minicpm-2b-128k'
tokenizer = AutoTokenizer.from_pretrained(path, eos_token_id=2, pad_token_id=2)
model = AutoModelForCausalLM.from_pretrained(path, torch_dtype=torch.bfloat16, device_map='cuda:7', trust_remote_code=True)
# model = AutoModelForCausalLM.from_pretrained(path, torch_dtype=torch.bfloat16, device_map='cuda:7', trust_remote_code=True, low_cpu_mem_usage=True)

responds, history = model.chat(tokenizer, "山东省最高的山是哪座山, 它比黄山高还是矮？差距多少？", temperature=0.8, top_p=0.8)
print(responds)
end_time = time.time()
print("程序运行时间：", end_time - start_time)

显卡显存：
![image](https://github.com/OpenBMB/MiniCPM/assets/58972326/928456d4-6489-4b3d-86dc-6f50394e567f)
![Uploading image.png…]()

运行结果
![Uploading image.png…]()

**Comment by jichaoqun** [comment]
补充：
当使用全部GPU，8卡3090进行推理的过程中，时间智慧更长

输出：
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
山东省最高的山是泰山，海拔1545米。

泰山比黄山高，两者相差约390米。
程序运行时间： 269.3435060977936

不知道是不是，应该在notbook上面那样，将模型加载好后，在进行推理，是不是时间会变短很多

**Comment by LDLINGLINGLING** [comment]
这个时间确实太长了，我猜测是否是cuda版本的原因？查下cuda和torch的匹配关系吧，按目前的信息，我只能知道这么多

**Comment by LDLINGLINGLING** [comment]
请问问题结局了么？生成长度是否非常大？
