### ISSUE TITLE
相同的问题，期待解决方案

### ISSUE THREAD

**Issue by haohenggang** [OpenBMB/MiniCPM#164]
相同的问题，期待解决方案

_Originally posted by @Single430 in https://github.com/OpenBMB/MiniCPM/issues/144#issuecomment-2158410669_
   兄弟，这个问题解决了吗

**Comment by LDLINGLINGLING** [comment]
We no longer maintain the mlc solution for android deployment

**Comment by chocolatezhu** [comment]
> 我们不再维护用于Android部署的mlc解决方案

请问有什么替代方案吗？

**Comment by LDLINGLINGLING** [comment]
llama.cpp和powerinfer，我在github的导航模块里面已经添加了

**Comment by chocolatezhu** [comment]
> llama.cpp和powerinfer，我在github的导航模块里面已经添加了

你好，你上面说的方案可以实现端测吗，可以接入到移动端 Android  APP 里吗？

**Comment by LDLINGLINGLING** [comment]
应该可以，但是会有一些工程问题

**Comment by chocolatezhu** [comment]
> llama.cpp

明白，请问基于 llama.cpp 方案的端测有详细的教程吗
