### ISSUE TITLE
[Bad Case]:  how can i use model.forward to inference model?

### ISSUE THREAD

**Issue by ziyanxzy** [OpenBMB/MiniCPM#165]
### Description / 描述

i want to use model(data) to inference model  instead of model.chat(input) to inference. how can i prepared the data?? 

### Case Explaination / 案例解释

i can not get the input dataformat for model.forward, because  i dont know the data["position_id"] in forward.

**Comment by LDLINGLINGLING** [comment]
You should pay more attention to the generate method, because the chat function is an encapsulated generate function, and the generate function is the encapsulated forward
