### ISSUE TITLE
how to start Instruct finetune by MiniCPM？

### ISSUE THREAD

**Issue by scalaboy** [OpenBMB/MiniCPM#167]
### Feature request  / 功能建议

In the finetune dir,the pipeline is train Q-A dataset, 
however,we need to finetune MiniCPM by Instruct tuning.
Is there any solutions?

**Comment by LDLINGLINGLING** [comment]
I think what we provide is a training method, which is sft. It should also be suitable for instruct tuning. If you have any questions, you can send us your data example.
