### ISSUE TITLE
训练loss正常，但是验证集loss是nan

### ISSUE THREAD

**Issue by lifelsl** [OpenBMB/MiniCPM#174]
我在用miniCPM-2B-sft-bf16时，想要微调做一个5分类任务，但是出现了训练loss正常，但是验证集loss是nan的问题，请问是什么原因导致的，我该怎么去修改

**Comment by lifelsl** [comment]
训练集loss一开始为0.4，微淘代码用的是提供的lora_finetune_ocnli.sh

**Comment by lifelsl** [comment]
数据已经检查过，没有问题

**Comment by LDLINGLINGLING** [comment]
提供日志吧，就这么看难看出来啊

**Comment by lifelsl** [comment]
已经解决了，就是数据集的问题，不好意思了，没检查仔细
