### ISSUE TITLE
  请扫微信二维码加群，如果群失效，可以添加我微信加入：yx116169

### ISSUE THREAD

**Issue by feihuamantian** [OpenBMB/MiniCPM#175]
### Description / 描述

拉了一个多模态大模型技术交流群，大家可以加入进来进行技术交流
![20240725-111054](https://github.com/user-attachments/assets/77ae583a-ffd7-488c-84fc-18054542e434)

**Comment by LDLINGLINGLING** [comment]
请勿重复发
