### ISSUE TITLE
在sft的过程中，我是个新手，我该如何选取最优的checkpoint，以及如何安排训练集和验证集的比例。

### ISSUE THREAD

**Issue by GromZhang** [OpenBMB/MiniCPM#181]
如标题。我在训练的过程中，有两次经历。第一次loss在0.7左右的时候开始收敛，但是在使用的过程中发现有些能力变现不佳。所以更新了新的训练数据集，新的训练数据集，正负样本比例是1：1，但是我发现loss不断的下滑，甚至下滑到了0.04，但是eval_loss只能到1.08。我该如何优化训练集以及如何分配训练集和验证集的比例？按照eval_Loss的最小值选取chechpoint的思路是正确的吗？

下面附上我的两个sft的trainer_state.json
[trainer_state.json](https://github.com/user-attachments/files/16423637/trainer_state.json)
[trainer_state_2.json](https://github.com/user-attachments/files/16423643/trainer_state_2.json)

**Comment by LDLINGLINGLING** [comment]
你好，eval_loss严格来说只能是一个粗略判断的手段，精确还是要看具体任务的评价指标，以及人工评判。因为大模型是生成式的，客观评价指标不是特别容易找。 另外我不太懂你说的负样本是什么意思。

**Comment by GromZhang** [comment]
> 你好，eval_loss严格来说只能是一个粗略判断的手段，精确还是要看具体任务的评价指标，以及人工评判。因为大模型是生成式的，客观评价指标不是特别容易找。 另外我不太懂你说的负样本是什么意思。
感谢老师，我说的正负样本大概类似于积极和消极文本分类任务中的两类。
那按照您说的意思，我只能通过反复的对测试数据集进行验证。比对准确和召回情况，才能判断哪一个是最佳的checkpoint是吗？是否还有其他的评估手段呢？

**Comment by LDLINGLINGLING** [comment]
确实你可以这么做，这样比较省事。也可以在改源代码，在训练过程设置回调函数直接测试文本的准确和召回以及F1分数。

**Comment by LDLINGLINGLING** [comment]
至于验证集的比例在数据集较小时可以维持20%左右，数据集大的话这个占比可以继续减少，这只是一个大致方向。

**Comment by GromZhang** [comment]
感谢老师的指导。我大致了解了。在测试的过程中我发现，eval_Loss的参考价值也比较大，我往往会选取loss和evalloss都比较小的checkpoint，效果也确实比较好一些。
