### ISSUE TITLE
[Bad Case]: error

### ISSUE THREAD

**Issue by lhjlhj11** [OpenBMB/MiniCPM#195]
### Description / 描述

cos = cos[position_ids].unsqueeze(unsqueeze_dim)  # [bs, 1, seq_len, dim]
IndexError: index is out of bounds for dimension with size 0

### Case Explaination / 案例解释

cos = cos[position_ids].unsqueeze(unsqueeze_dim)  # [bs, 1, seq_len, dim]
IndexError: index is out of bounds for dimension with size 0

**Comment by LDLINGLINGLING** [comment]
请问使用哪个模型的代码出错
