### ISSUE TITLE
请问embedding模型和rerank模型怎么finetune，用的FlagEmbedding的吗？

### ISSUE THREAD

**Issue by LIUKAI0815** [OpenBMB/MiniCPM#196]

**Comment by ericxk** [comment]
+1

**Comment by Kaguya-19** [comment]
可以将weighted_mean pooling hack进FlagEmbedding框架进行适配

**Comment by Kaguya-19** [comment]
@ericxk @LIUKAI0815 我们现已支持Sentence Transformers库，详见https://huggingface.co/openbmb/MiniCPM-Embedding
