### ISSUE TITLE
[Feature Request]: vllm 能直接用functioncall？

### ISSUE THREAD

**Issue by lonngxiang** [OpenBMB/MiniCPM#198]
### Feature request  / 功能建议

vllm 能直接用functioncall？直接命令行vllm后台运行推理readme形式

**Comment by LDLINGLINGLING** [comment]
我们给出了vllm的functioncall代码。在github主页上有地址

**Comment by lonngxiang** [comment]
> 我们给出了vllm的functioncall代码。在github主页上有地址

现在使用必须安装这边vllm的分支吗，还是最新的vllm 0.6支持了吗

**Comment by LDLINGLINGLING** [comment]
目前还要用我们的分支

**Comment by qq745639151** [comment]
> 我们给出了vllm的functioncall代码。在github主页上有地址

我试着运行了下，提示Model architectures ['MiniCPM3ForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'DeepseekV2ForCausalLM', 'ExaoneForCausalLM', 'FalconForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'JAISLMHeadModel', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'MiniCPMForCausalLM', 'NemotronForCausalLM', 'OlmoForCausalLM', 'OPTForCausalLM', 'OrionForCausalLM', 'PersimmonForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'PhiMoEForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'ArcticForCausalLM', 'XverseForCausalLM', 'Phi3SmallForCausalLM', 'MedusaModel', 'EAGLEModel', 'MLPSpeculatorPreTrainedModel', 'JambaForCausalLM', 'GraniteForCausalLM', 'MistralModel', 'Blip2ForConditionalGeneration', 'ChameleonForConditionalGeneration', 'FuyuForCausalLM', 'InternVLChatModel', 'LlavaForConditionalGeneration', 'LlavaNextForConditionalGeneration', 'MiniCPMV', 'PaliGemmaForConditionalGeneration', 'Phi3VForCausalLM', 'UltravoxModel', 'BartModel', 'BartForConditionalGeneration']

**Comment by qq745639151** [comment]
> 目前还要用我们的分支

vllm卡在 buiding wheel这里了，没日志输出，求助怎么确定问题

**Comment by lonngxiang** [comment]
> > 目前还要用我们的分支
> 
> vllm卡在 buiding wheel这里了，没日志输出，求助怎么确定问题，命令行界面： ![image](https://private-user-images.githubusercontent.com/39238149/365021027-57567514-e659-4f6e-b36f-aefc082724fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTI1NzcsIm5iZiI6MTcyNTU5MjI3NywicGF0aCI6Ii8zOTIzODE0OS8zNjUwMjEwMjctNTc1Njc1MTQtZTY1OS00ZjZlLWIzNmYtYWVmYzA4MjcyNGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAzMTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYTI4ZmE5YjkxNzE1ZmM2ODMyM2M3YTk2NGMwM2Q0YzQwZWZjNjFmMzAzMDk3MTNjZjdmZTcxZThjNDliNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_ZQ9Fa2TigP1PIhadVmy0QooxzPA4dp35Vt0FzlD_M)

一样

![image](https://github.com/user-attachments/assets/aa6f003d-72f3-4e13-865b-14d51cb944c2)

**Comment by LDLINGLINGLING** [comment]
把代码git下载，再安装呢？

**Comment by qq745639151** [comment]
> > > 目前还要用我们的分支
> > 
> > 
> > vllm卡在 buiding wheel这里了，没日志输出，求助怎么确定问题，命令行界面： ![image](https://private-user-images.githubusercontent.com/39238149/365021027-57567514-e659-4f6e-b36f-aefc082724fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTI1NzcsIm5iZiI6MTcyNTU5MjI3NywicGF0aCI6Ii8zOTIzODE0OS8zNjUwMjEwMjctNTc1Njc1MTQtZTY1OS00ZjZlLWIzNmYtYWVmYzA4MjcyNGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAzMTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYTI4ZmE5YjkxNzE1ZmM2ODMyM2M3YTk2NGMwM2Q0YzQwZWZjNjFmMzAzMDk3MTNjZjdmZTcxZThjNDliNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_ZQ9Fa2TigP1PIhadVmy0QooxzPA4dp35Vt0FzlD_M)
> 
> 一样
> 
> ![image](https://private-user-images.githubusercontent.com/40717349/365021160-aa6f003d-72f3-4e13-865b-14d51cb944c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTcyMDksIm5iZiI6MTcyNTU5NjkwOSwicGF0aCI6Ii80MDcxNzM0OS8zNjUwMjExNjAtYWE2ZjAwM2QtNzJmMy00ZTEzLTg2NWItMTRkNTFjYjk0NGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA0MjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NWFjMjUwZGJkODIwYzRkMGRmY2QzYWViZDY2MmEyMDNhNjIyMGI4YWUzODAyMTExYWIwOGNjOGVhY2YwMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E2m_iB5RaNELzZdl2Z2hDVCX5rnaan12lGF_5vHQPKo)

我这里OK了，就是特别慢
