### ISSUE TITLE
[Bug]: Model architectures ['MiniCPM3ForCausalLM'] are not supported for now.

### ISSUE THREAD

**Issue by qq745639151** [OpenBMB/MiniCPM#199]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

我试用了下官方给的functioncall的demo，提示模型框架还不支持

### To Reproduce / 如何复现

下载官方代码
安装requirements.txt的三方库， vllm ，datamodel_code_generator
然后运行

### Expected behavior / 期望的结果

能正确运行functioncall功能

### Screenshots / 截图

![image](https://github.com/user-attachments/assets/416a7198-d176-4bfa-9a4c-bedf24632754)

### Environment / 环境

```shell
autodl的机器

PyTorch  2.1.2
Python  3.10(ubuntu22.04)
Cuda  11.8
GPU A40(48GB) * 1
CPU 15 vCPU Intel(R) Xeon(R) Platinum 8358P CPU @ 2.60GHz
```

**Comment by AlphaINF** [comment]
same issue， 后来是怎么解决的

**Comment by thunder95** [comment]
same issue

**Comment by qq745639151** [comment]
要安装minicpm自己的vllm,     
```shell
pip install git+https://github.com/OpenBMB/vllm.git@minicpm3
````

**Comment by ML-GCN** [comment]
> 要安装minicpm自己的vllm,
> 
> ```shell
> pip install git+https://github.com/OpenBMB/vllm.git@minicpm3
> ```

有打包好的镜像下载地址没 可以运行cpm3的
