### ISSUE TITLE
可否提供一个 无限长上下文 MapReduce 的 sample code？

### ISSUE THREAD

**Issue by msxfXF** [OpenBMB/MiniCPM#201]
### Feature request  / 功能建议

可否提供一个 无限长上下文 MapReduce 的 sample code？

**Comment by shuo-git** [comment]
你好，当前代码还不包括MapReduce的功能，MiniCPM3 x MapReduce 的代码将在一周内开源

**Comment by msxfXF** [comment]
好的，谢谢

**Comment by shuo-git** [comment]
您好，请参考开源仓库：https://github.com/thunlp/LLMxMapReduce
详细技术报告近期会公开
