### ISSUE TITLE
[Feature Request]: emebdding&reranker服务问题

### ISSUE THREAD

**Issue by lyj157175** [OpenBMB/MiniCPM#207]
### Feature request  / 功能建议

请问什么框架可以提供mini-embedding和mini-reranker的推理服务，transformers推理好像不能直接支持异步

**Comment by Kaguya-19** [comment]
我们可以将encode转为异步函数，然后用fastapi启服务，周一我会给出demo

**Comment by Kaguya-19** [comment]
> 谢谢。但是我测试下来好像还没有原来的方式快

这里的demo是按条来进行推理的，实际部署可以根据情况按batch推理
