### ISSUE TITLE
[Bad Case]: MIniCPM3 原始pytorch .bin文件转为gguf失败

### ISSUE THREAD

**Issue by sataliulan** [OpenBMB/MiniCPM#212]
### Description / 描述

我按照指示，配置了llama_cpp环境，在执行模型转换时（命令：python convert_hf_to_gguf.py cpm_model_dir/MiniCPM3-4B/  --outfile cpm_model_dir/MiniCPM3-4B/CPM-4B-F16.gguf），提示错误：
ERROR:hf-to-gguf:Model MiniCPM3ForCausalLM is not supported
不知道是否是版本问题，还是目前的模型不支持最新的llama_cpp版本，截图如下：
![image](https://github.com/user-attachments/assets/3550cbbe-838c-43a0-b65b-daea2eddbfe5)（注，本机机器默认python环境为python3）

**Comment by luckfu** [comment]
同样，我以为原版llama.cpp不行，又从openBMB clone了一次llama.cpp 依然不行

**Comment by jason-ni** [comment]
我今天转成功了，中间也出现了错误，仔细看报错，我这里是缺少jsonschema datamodel_code_generator 这两个包。装了重新转就可以了。

**Comment by luckfu** [comment]
> 我今天转成功了，中间也出现了错误，仔细看报错，我这里是缺少jsonschema datamodel_code_generator 这两个包。装了重新转就可以了。

可以提供下版本吗？我的报错信息没有多余的包错误信息呢
```bash
python convert_hf_to_gguf.py models/MiniCPM3-4B --outfile models/MiniCPM3-4B-f16.gguf
INFO:hf-to-gguf:Loading model: MiniCPM3-4B
ERROR:hf-to-gguf:Model MiniCPM3ForCausalLM is not supported
```

**Comment by sataliulan** [comment]
@jason-ni +1,还请告知下环境版本信息，方便的话请提供下您虚拟环境的requirement文件

**Comment by sataliulan** [comment]
成功了，不能使用llama.cpp官方repo，需要使用cpm 的llama.cpp会经历与@jason-ni 同样的缺少包的问题

**Comment by nctu6** [comment]
git checkout minicpm3

This fixed convert_hf_to_gguf.py is not merged into main branch.

Regards.

**Comment by bioinformatist** [comment]
> This fixed convert_hf_to_gguf.py is not merged into main branch.

PR link: https://github.com/ggerganov/llama.cpp/pull/9322
