### ISSUE TITLE
[Bad Case]: 运行Function call 简易实现代码出错，未调用相当的Function 

### ISSUE THREAD

**Issue by heiheiheibj** [OpenBMB/MiniCPM#218]
### Description / 描述

运行 https://modelbest.feishu.cn/wiki/LrdMwKKt3iZgoYkQlPRcvY1PnXc 页面的 
Function call 简易实现（更细致、更高效请看[【再聊agent】Function call 详解] 代码
输出的 response 内容为
I'm sorry, but as an AI assistant, I don't have access to personal data about individuals unless it has been shared with me during our conversation. I also don't have real-time access to external systems or databases to check order status. My primary function is to provide general information and assist with queries to the best of my knowledge and abilities. I recommend reaching out to the store or service provider directly for information about your order. They should be able to provide you with the most up-to-date information regarding your delivery date.
并不是预期的内容
所以 call_str=get_response_call(response) 返回 None
print(eval(call_str)) 就出错了

**Comment by LDLINGLINGLING** [comment]
你好，这只是一个简易的实现，应该是采样参数不一致导致我们输出的结果有差异，请设置do_sample=False。
