### ISSUE TITLE
MiniCPM可以微调做文本分类任务吗

### ISSUE THREAD

**Issue by lifelsl** [OpenBMB/MiniCPM#219]
我是一个新手，如果我想微调MiniCPM做文本分类任务，我该怎么做

**Comment by LDLINGLINGLING** [comment]
简单的方法就是，根据微调教程，将输入改成需要分类的文本，可能的分类，输出是分类的label。

例如：
        输入：请帮我将以下文本进行分类，类别为肯定或者否定的一种，文本是：你的工作我非常满意。
        输出：肯定
