### ISSUE TITLE
[Bad Case]: readme中llama.cpp的安装顺序是否应该调整

### ISSUE THREAD

**Issue by SuperAZHE** [OpenBMB/MiniCPM#221]
### Description / 描述

安装 llama.cpp
  git clone https://github.com/OpenBMB/llama.cpp.git
  **git checkout minicpm3
  cd llama.cpp**
  make 
  ------我本地试了一下，按这个顺序执行，git checkout会报错，这块是否应该先cd llama.cpp然后再git checkout创建branch

### Case Explaination / 案例解释

一个步骤顺序上的小小建议

**Comment by LDLINGLINGLING** [comment]
非常感谢您宝贵的意见
