### ISSUE TITLE
能详细展开说一下提出的 “LLM x MapReduce” 么

### ISSUE THREAD

**Issue by zhjunqin** [OpenBMB/MiniCPM#225]
### Feature request  / 功能建议

请问提到

原生支持 32k 上下文长度，32k 长度内大海捞针全绿。提出 LLM x MapReduce ，理论可处理的上下文长度达到 +∞

能详细展开说一下提出的  “LLM x MapReduce” 么？

**Comment by shuo-git** [comment]
您好，请参考一下开源仓库：https://github.com/thunlp/LLMxMapReduce
详细技术报告近期会公开
