### ISSUE TITLE
[Feature Request]:  MiniCPM-Embedding、MiniCPM-Reranker会基于MiniCPM3再发新版吗？

### ISSUE THREAD

**Issue by dkasa** [OpenBMB/MiniCPM#228]
### Feature request  / 功能建议

MiniCPM-Embedding、MiniCPM-Reranker会基于MiniCPM3再发新版吗？

**Comment by Kaguya-19** [comment]
4B参数量对于Retriever和Reranker有些大，我们暂时没有想法
