### ISSUE TITLE
[Feature Request]: Need Docker image for OpenBMB/llama.cpp

### ISSUE THREAD

**Issue by bioinformatist** [OpenBMB/MiniCPM#231]
### Feature request  / 功能建议

Since the PR https://github.com/ggerganov/llama.cpp/pull/9322 still has been settling, could you provide a Docker image for current version of https://github.com/OpenBMB/llama.cpp/tree/minicpm3?

I want to convert the model to `.gguf` format and quantize it, and it can be cool if there's no need for compiling the `llama.cpp`.

Or could you upload the quantized version in `.gguf` format to HuggingFace?

Thanks in advance!

**Comment by zh-zheng** [comment]
Hi, thanks for the attention.
We have provided MiniCPM3 models in GGUF format (fp16 and q4). Check [here](https://huggingface.co/openbmb/MiniCPM3-4B-GGUF).
