### ISSUE TITLE
General Question: Which framework do you use to evaluate MiniCPM3-4B?

### ISSUE THREAD

**Issue by xunkai55** [OpenBMB/MiniCPM#234]
Hi there,

I tried to evaluate MiniCPM3-4B by my self (deployed locally with OpenBMB/vllm) with OpenAI/simple-evals but got weirdly low scores, i.e. MMLU = 59.8. Before digging it deeper, I'd like to know which evaluation framework do you use.

Thanks a lot!

**Comment by zh-zheng** [comment]
Hi, you can use [OpenCompass](https://opencompass.org.cn/home).
