### ISSUE TITLE
使用llamafactory微调报错

### ISSUE THREAD

**Issue by lifelsl** [OpenBMB/MiniCPM#238]
我在使用llamafactory微调cpm3时发生了这个错误
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data2/liushuliang/MiniCPM/LLaMA-Factory/src/train.py", line 28, in <module>
[rank0]:     main()
[rank0]:   File "/data2/liushuliang/MiniCPM/LLaMA-Factory/src/train.py", line 19, in main
[rank0]:     run_exp()
[rank0]:   File "/data2/liushuliang/MiniCPM/LLaMA-Factory/src/llamafactory/train/tuner.py", line 50, in run_exp
[rank0]:     run_sft(model_args, data_args, training_args, finetuning_args, generating_args, callbacks)
[rank0]:   File "/data2/liushuliang/MiniCPM/LLaMA-Factory/src/llamafactory/train/sft/workflow.py", line 47, in run_sft
[rank0]:     dataset_module = get_dataset(template, model_args, data_args, training_args, stage="sft", **tokenizer_module)
[rank0]:   File "/data2/liushuliang/MiniCPM/LLaMA-Factory/src/llamafactory/data/loader.py", line 248, in get_dataset
[rank0]:     dataset = _get_merged_dataset(data_args.dataset, model_args, data_args, training_args, stage)
[rank0]:   File "/data2/liushuliang/MiniCPM/LLaMA-Factory/src/llamafactory/data/loader.py", line 154, in _get_merged_dataset
[rank0]:     for dataset_attr in get_dataset_list(dataset_names, data_args.dataset_dir):
[rank0]:   File "/data2/liushuliang/MiniCPM/LLaMA-Factory/src/llamafactory/data/parser.py", line 94, in get_dataset_list
[rank0]:     raise ValueError("Cannot open {} due to {}.".format(config_path, str(err)))
[rank0]: ValueError: Cannot open data/dataset_info.json due to [Errno 2] No such file or directory: 'data/dataset_info.json'.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/data2/liushuliang/MiniCPM/LLaMA-Factory/src/llamafactory/data/parser.py", line 90, in get_dataset_list
[rank1]:     with open(config_path, "r") as f:
[rank1]: FileNotFoundError: [Errno 2] No such file or directory: 'data/dataset_info.json'
但是我已经配置过这些文件了
<img width="302" alt="屏幕截图 2024-09-15 113145" src="https://github.com/user-attachments/assets/b2f47e99-60f8-4c00-839c-7ed936977039">

<img width="279" alt="屏幕截图 2024-09-15 113209" src="https://github.com/user-attachments/assets/452f156d-0838-4696-b074-02cc63b85b12">
<img width="436" alt="屏幕截图 2024-09-15 113234" src="https://github.com/user-attachments/assets/74510273-927c-48ce-8426-07507dd93931">
请问一下我的问题出现在哪里

**Comment by LDLINGLINGLING** [comment]
你好，你的 'data/dataset_info.json'并没有再llamafactory的data路径下

**Comment by lifelsl** [comment]
感谢你的回复，非常抱歉假期打扰你们，但我还是没能理解你的意思，能否详细解释一下，我是按照你们给的教程建立的minicpm3这个文件夹
<img width="646" alt="屏幕截图 2024-09-17 174518" src="https://github.com/user-attachments/assets/79a583da-90c8-405b-babe-ef2e6ba40739">

**Comment by LDLINGLINGLING** [comment]
最后一行代码的含义是，将你MiniCPM下创建的所有文件（包括yaml和bash）整个文件夹，复制到llamafactory的examples路径下

**Comment by lifelsl** [comment]
你好，我去看了b站你们提供的用llamafactory微调minicpm的视频，跟着他的步骤来，还是出现找不到data/dataset_info.json的问题
