### ISSUE TITLE
[Bug]: lora微调模型无法在vllm加载

### ISSUE THREAD

**Issue by Caismis** [OpenBMB/MiniCPM#241]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

按照官方教程进行lora微调和模型合并保存后，调用vllm serve无法加载模型，报
>ValueError: Model architectures ['MiniCPM3Model'] are not supported for now. Supported architectures: ['MiniCPM3ForCausalLM', 'MiniCPM3Model', 'AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'Blip2ForConditionalGeneration', 'ChameleonForConditionalGeneration', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'DeepseekV2ForCausalLM', 'FalconForCausalLM', 'FuyuForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'InternVLChatModel', 'JAISLMHeadModel', 'LlamaForCausalLM', 'LlavaForConditionalGeneration', 'LlavaNextForConditionalGeneration', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'MiniCPMForCausalLM', 'MiniCPMV', 'NemotronForCausalLM', 'OlmoForCausalLM', 'OPTForCausalLM', 'OrionForCausalLM', 'PersimmonForCausalLM', 'PaliGemmaForConditionalGeneration', 'PhiForCausalLM', 'Phi3ForCausalLM', 'Phi3VForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'ArcticForCausalLM', 'XverseForCausalLM', 'Phi3SmallForCausalLM', 'MedusaModel', 'MLPSpeculatorPreTrainedModel', 'JambaForCausalLM', 'MistralModel']
查看模型的`config.json`显示模型`architectures`为`MiniCPM3Model`而非base模型中的`MiniCPM3ForCausalLM`

### To Reproduce / 如何复现

按照[官方llama factory教程](https://modelbest.feishu.cn/wiki/PpUrwsmDAiAAoEk8jc8cnBh7nOh)，对示例dpo数据采取lora微调，并按[官方教程](https://modelbest.feishu.cn/wiki/MPkPwvONEiZm3BkWMnyc83Tin4d)对模型进行合并保存，通过vllm serve调用后报错

### Expected behavior / 期望的结果

正常运行微调模型

### Environment / 环境

```shell
- OS: wsl2-Ubuntu 
- Pytorch: torch 2.4.0
- Device: RTX 4090
python环境和[官方教程](https://modelbest.feishu.cn/docx/ATfTdGsSXotRDex0OzycvRjsn0e)中一致
```

**Comment by LDLINGLINGLING** [comment]
你好，手动修改config文件试一试吧

**Comment by Caismis** [comment]
尝试了修改为MiniCPM3ForCausalLM和MiniCPMModel，均报错，前者在加载模型bin文件时出错

**Comment by Caismis** [comment]
当把config文件中改成`MiniCPM3ForCausalLM`时，报
File "/home/.local/lib/python3.10/site-packages/sglang/srt/models/minicpm3.py", line 650, in load_weights
    param = params_dict[name]
KeyError: 'embed_tokens.weight'
, detoken_init_state: init ok
改成`MiniCPMForCausalLM`时，报
RuntimeError: The size of tensor a (16) must match the size of tensor b (32) at non-singleton dimension 0
, detoken_init_state: init ok
