### ISSUE TITLE
训练时训练了一阵子后进度条会卡住 有人遇到这种情况吗

### ISSUE THREAD

**Issue by Hoyxxx** [OpenBMB/MiniCPM#251]
### Description / 描述

训练时训练了一阵子后进度条会卡住不动了 有人遇到这种情况吗

**Comment by LDLINGLINGLING** [comment]
请问你用的是llamafactory么

**Comment by Hoyxxx** [comment]
> 请问你用的是llamafactory么

yes

**Comment by LDLINGLINGLING** [comment]
您好，这个估计是llamafactory的环境问题，可能你到llamafactory的社区提issue更加合适

**Comment by Hoyxxx** [comment]
> 您好，这个估计是llamafactory的环境问题，可能你到llamafactory的社区提issue更加合适
ok 谢谢
