### ISSUE TITLE
[Question]: did MiniCPM3 support `FIM` prompt?

### ISSUE THREAD

**Issue by zwpaper** [OpenBMB/MiniCPM#257]
### Feature request  / 功能建议

currnetly many LLM models support the `FIM(fill-in-the-middle)` prompt, it's helpful for code generation, but I did not find any related info with MiniCPM3, can you clarify this for us?

Thanks for the great model!

**Comment by saurabh12453** [comment]
This is to be done on very important response that's periotty bases

**Comment by saurabh12453** [comment]
No it's doesn't support

**Comment by zh-zheng** [comment]
> ok, thanks for the reply, is there any plan to add the support?

Yes, in the near future.

**Comment by saurabh12453** [comment]
Yes, I do.
