### ISSUE TITLE
[Feature]: Docker Support

### ISSUE THREAD

**Issue by soulteary** [OpenBMB/MiniCPM#27]
### Feature request  / 功能建议

开箱即用的 Docker 环境，可以让更多人玩起来，也更容易进行基于模型的开发，或者和其他模型联动。

- [ ] HF
- [ ] VLLM (use latest CUDA & Torch & etc... faster and faster)

我基于 Nvidia 最新版本的月度容器做了一个简单的封装（代码 merge 了 pr 里的 code，方便容器使用和避免输出 warning）：

https://github.com/soulteary/docker-mini-cpm

hope it helps.

**Comment by THUCSTHanxu13** [comment]
老哥你方便pull requests一下嘛

**Comment by soulteary** [comment]
才看到，我整一个
