### ISSUE TITLE
[Feature Request]: openbmb/MiniCPM-2B-dpo-fp16 最大上下文长度是多少呢？

### ISSUE THREAD

**Issue by mailtobshen** [OpenBMB/MiniCPM#32]
### Feature request  / 功能建议

openbmb/MiniCPM-2B-dpo-fp16 最大上下文长度是多少呢？也没看到官方说明，配置文件里好像也没找到，谁回答下好吗？

**Comment by SwordFaith** [comment]
At the moment, the context length is set to 4k tokens. A longer version may or may not be released for open-source access.
