### ISSUE TITLE
什么时候备案呢？

### ISSUE THREAD

**Issue by dara0418** [OpenBMB/MiniCPM#34]
### Feature request  / 功能建议

你好，感谢开源性价比这么高的大模型。有计划进行国内的生成式模型备案吗？

**Comment by Jinnrry** [comment]
？？？？？？？？？

开源一个技术方案，备案？这么讽刺的吗

**Comment by D3-3109** [comment]
你没事吧？

**Comment by dara0418** [comment]
我其实也没弄清楚，如果我使用开源大模型提供服务，只需要我自己去备案吗，还是需要开源模型的发行方也一起备案呢？我看隔壁的ChatGLM已经备案了。

**Comment by D3-3109** [comment]
这个项目不提供在线服务，不涉及在国内取得 ICP许可证，备案之类的情况，其次，项目涉及的 APP 的分发渠道也不在国内，也不需要 APP 备案，这是一个开源模型，你要想在内地提供服务，那请自己组建公司，自己做了产品然后依据生成式人工智能服务管理暂行办法进行备案，开源项目做不到这些

**Comment by dara0418** [comment]
好的，了解了，感谢指导。

**Comment by Pickpate** [comment]
> 我其实也没弄清楚，如果我在国内使用开源大模型提供服务，只需要我自己去备案吗，还是需要开源模型的发行方也一起备案呢？我看隔壁的ChatGLM已经备案了。

其实为了促进模型的采用，确实有一些开源方会去备案，因为如果不备案的话，一些国内公司可能不敢用这个模型对外提供服务。
