### ISSUE TITLE
[Feature Request]: Mention number of A100 GPU hours

### ISSUE THREAD

**Issue by casper-hansen** [OpenBMB/MiniCPM#36]
### Feature request  / 功能建议

Llama 2 shares the number of A100 GPUs hours used for training their models. It would be amazing to have an equivalent number of GPU hours for the MiniCPM models because this will make it easier to demonstrate the effectivity of the various methods used to parameter-efficiently train the model.

||Time (GPU hours)|Power Consumption (W)|Carbon Emitted(tCO<sub>2</sub>eq)|
|---|---|---|---|
|Llama 2 7B|184320|400|31.22|
|Llama 2 13B|368640|400|62.44|
|Llama 2 70B|1720320|400|291.42|
|Total|3311616||539.00|

Source: https://github.com/facebookresearch/llama/blob/main/MODEL_CARD.md#hardware-and-software

**Comment by ShengdingHu** [comment]
To accelerate the training speed of MiniCPM, we did not fully utilize the memory of the A100 GPUs (each A100 GPU was used less than 20GB). We deployed 160 A100 GPUs, and the training took approximately 15 days, amounting to a total of 15 * 24 * 160 = 57,600 A100 GPU hours. Note that this doesn't take into account the GPU hours used for doing decay experiments, scaling law experiment. 
为了加快MiniCPM的训练速度，我们没有完全利用A100 GPU的显存（每个A100 GPU的使用量不到20GB）。我们使用了160个A100 GPU，训练时间大约为15天，因此总共使用了15 * 24 * 160 = 57600个A100 GPU小时。注意，以上时间不包括做退火的对照实验，scaling law相关的实验的时间。
