### ISSUE TITLE
Compare with Qwen1.8B?

### ISSUE THREAD

**Issue by lucasjinreal** [OpenBMB/MiniCPM#39]
Compare with Qwen1.8B?

**Comment by SwordFaith** [comment]
![image](https://github.com/OpenBMB/MiniCPM/assets/18397468/6c619872-d0df-42c3-91a4-03fcf9027486)
We have presented a comparative evaluation with current mainstream small language models in our technical report. You can find more details in our technical report: https://shengdinghu.notion.site/MiniCPM-Unveiling-the-Potential-of-End-side-Large-Language-Models-d4d3a8c426424654a4e80e42a711cb20

**Comment by lucasjinreal** [comment]
@SwordFaith  Is there any way converts MiniCPM to llama like weights and load using tansformers vanilla llama arch？
