### ISSUE TITLE
[Bug]: Exception ValueError when running inference example

### ISSUE THREAD

**Issue by bismack163** [OpenBMB/MiniCPM#41]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

Exception when running the example:
_python inference.py --model_path <vllmcpm_repo_path> --prompt_path prompts/prompt_demo.txt_

ValueError: The checkpoint you are trying to load has model type `cpm_dragonfly` but Transformers does not recognize this architecture. This could be because of an issue with the chec
kpoint, or because your version of Transformers is out of date.

### To Reproduce / 如何复现

Follow quick setup guide to setup on Ubuntu 20.04 and python 3.10
Run example:
cd inference/vllm/examples/infer_cpm
python inference.py --model_path <vllmcpm_repo_path> --prompt_path prompts/prompt_demo.txt

### Expected behavior / 期望的结果

Run the example without error

### Environment / 环境

```shell
- OS: Ubuntu 20.04
- Pytorch: torch 2.2.0
- CUDA: CUDA 12.0
- Device: RTX3080
```

### Additional context / 其他信息

Below patch workaround the problem:
```
diff --git a/inference/vllm/vllm/transformers_utils/config.py b/inference/vllm/vllm/transformers_utils/config.py
index 15ca432..625952c 100644
--- a/inference/vllm/vllm/transformers_utils/config.py
+++ b/inference/vllm/vllm/transformers_utils/config.py
@@ -38,7 +38,7 @@ def get_config(model: str,
                 raise RuntimeError(err_msg) from e
             else:
                 raise e
-    except KeyError as e:
+    except ValueError as e:
         if os.path.exists(model):
             config = {}
             with open(f"{model}/config.json", 'r') as fin:
```

**Comment by SUDA-HLT-ywfang** [comment]
Hi,
do you convert hf model files to vllm-based format like the tutorial in readme?
<img width="863" alt="image" src="https://github.com/OpenBMB/MiniCPM/assets/47963924/26e3f9ef-dab0-4668-889b-cb0880e5b993">

**Comment by bismack163** [comment]
> Hi, do you convert hf model files to vllm-based format like the tutorial in readme? <img alt="image" width="863" src="https://private-user-images.githubusercontent.com/47963924/302101505-26e3f9ef-dab0-4668-889b-cb0880e5b993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTc2NzQsIm5iZiI6MTcwNzA5NzM3NCwicGF0aCI6Ii80Nzk2MzkyNC8zMDIxMDE1MDUtMjZlM2Y5ZWYtZGFiMC00NjY4LTg4OWItY2IwODgwZTViOTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAxNDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NjQxOTY0M2YxZjFkZTBlMTM0MmI3MzEzODY1NmRkYTg2NzdmZDJhMDY0MjE5Y2Y4YWY0ZDMyYzUwNzg5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HRZeHO8I6aq5DlHh8KDoRzoPqT6uAVfIHKYlEMYm9Yc">

Yes

**Comment by sunbeibei-hub** [comment]
i get the error, too.
```
(bei_MiniCPM) [search@search-chatGLM-02 infer_cpm]$ python inference.py --model_path /data/search/bei/MiniCPM/vllmcpm_MiniCPM-2B-dpo-fp16  --prompt_path prompts/prompt_demo.txt
Traceback (most recent call last):
  File "/home/search/miniconda3/envs/bei_MiniCPM/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1117, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/search/miniconda3/envs/bei_MiniCPM/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 813, in __getitem__
    raise KeyError(key)
KeyError: 'cpm_dragonfly'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/search/bei/MiniCPM/inference/vllm/examples/infer_cpm/inference.py", line 43, in <module>
    llm = LLM(model=args.model_path, tensor_parallel_size=1, dtype='bfloat16')
  File "/home/search/miniconda3/envs/bei_MiniCPM/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 93, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/home/search/miniconda3/envs/bei_MiniCPM/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 225, in from_engine_args
    engine_configs = engine_args.create_engine_configs()
  File "/home/search/miniconda3/envs/bei_MiniCPM/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 187, in create_engine_configs
    model_config = ModelConfig(self.model, self.tokenizer,
  File "/home/search/miniconda3/envs/bei_MiniCPM/lib/python3.10/site-packages/vllm/config.py", line 91, in __init__
    self.hf_config = get_config(self.model, trust_remote_code, revision)
  File "/home/search/miniconda3/envs/bei_MiniCPM/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 40, in get_config
    raise e
  File "/home/search/miniconda3/envs/bei_MiniCPM/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 28, in get_config
    config = AutoConfig.from_pretrained(
  File "/home/search/miniconda3/envs/bei_MiniCPM/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1119, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `cpm_dragonfly` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

**Comment by sunbeibei-hub** [comment]
https://github.com/OpenBMB/MiniCPM/issues/9
transforms version have question

**Comment by ShengdingHu** [comment]
Sorry for the inconvenience, we will look into this bug very soon.

**Comment by huangyuxiang03** [comment]
Sorry for the inconvenience, could you try transformers==4.34.0? It seems like the error handling part has been changed in current version of transformers. We will fix `inference/vllm/vllm/transformers_utils/config.py` soon.

**Comment by huangyuxiang03** [comment]
It seems like this problem is caused by incorrect version of transformers. Please use transformers==4.34.0 and refer to [#9](https://github.com/OpenBMB/MiniCPM/issues/9)
