### ISSUE TITLE
[Feature Request]: 能补充一下 lora 训练后加载的例子吗？

### ISSUE THREAD

**Issue by dogvane** [OpenBMB/MiniCPM#46]
### Feature request  / 功能建议

lora训练文档里关于训练数据结构里，写的是 conversations，实际代码里用 message，也一并把这部分文档改一下。

**Comment by THUCSTHanxu13** [comment]
这个文档里面（https://huggingface.co/blog/peft），hugginface给了peft的load和save说明，我们也会在我们的文件里面补充，感谢您的建议。
