### ISSUE TITLE
[Feature Request]: MiniCPM 训练的batch_size是4M，怎么解释

### ISSUE THREAD

**Issue by sunshineflg** [OpenBMB/MiniCPM#50]
### Feature request  / 功能建议

![企业微信截图_20240205180051](https://github.com/OpenBMB/MiniCPM/assets/24838515/88cceea5-56f2-435c-abdd-a0d041f1bcad)
模型训练时使用的batch size是4M，这个4M是400万吗？一个batch,用400万example？

**Comment by THUCSTHanxu13** [comment]
tokens

**Comment by zizhec** [comment]
那每个sample是多少token？

**Comment by nmd2k** [comment]
Thanks for clarify 🤣
