### ISSUE TITLE
The same output 

### ISSUE THREAD

**Issue by pribadihcr** [OpenBMB/MiniCPM#56]
Hi, I tried to infer MiniCPM-V different images in loops. But got the same result.
```
images = ["a.jpg", "b.jpg", "c.jpg"]

for img in images:
     image = Image.open(image_path).convert('RGB')
     res, context, _ = model.chat(
            image=image,
            msgs=msgs,
            context=None,
            tokenizer=tokenizer,
            sampling=False,
            temperature=0.0
        )
     print(res)
```
the "res" has the same output.

**Comment by THUCSTHanxu13** [comment]
please  change "image = Image.open(image_path).convert('RGB')" to "image = Image.open(img).convert('RGB')"

**Comment by THUCSTHanxu13** [comment]
everytime you open the file "image_path" rather than "img"

**Comment by pribadihcr** [comment]
@THUCSTHanxu13 ,

Sorry, actually may issue still exist. 

```
images = ["a.jpg", "b.jpg", "c.jpg"]

for img in images:
     image = Image.open(img).convert('RGB')
     res, context, _ = model.chat(
            image=image,
            msgs=msgs,
            context=None,
            tokenizer=tokenizer,
            sampling=False,
            temperature=0.0
        )
     print(res)
```

**Comment by ShengdingHu** [comment]
Do you still have questions? @pribadihcr

**Comment by pribadihcr** [comment]
> @THUCSTHanxu13 ,
> 
> Sorry, the issue still exists.
> 
> ```
> images = ["a.jpg", "b.jpg", "c.jpg"]
> 
> for img in images:
>      image = Image.open(img).convert('RGB')
>      res, context, _ = model.chat(
>             image=image,
>             msgs=msgs,
>             context=None,
>             tokenizer=tokenizer,
>             sampling=False,
>             temperature=0.0
>         )
>      print(res)
> ```

@ShengdingHu, with the script above give the same output. Please double check with reproduce it. Thank you.

**Comment by YuzaChongyi** [comment]
@pribadihcr You should put msgs inside the for loop，because msgs are updated when called model.chat
