### ISSUE TITLE
[Feature Request]: 支持Apple Silicon推理

### ISSUE THREAD

**Issue by jinyuanZhou-Leo** [OpenBMB/MiniCPM#6]
### Feature request  / 功能建议

安装vllm会提示 `Cannot find CUDA_HOME. CUDA must be available to build the package`

**Comment by ShengdingHu** [comment]
vllm暂时不支持 apple silicon
vllm currently doesn't support apple silicon. 
我们几天后会更新cpp代码
We will update cpp code in a few days

**Comment by huangyuxiang03** [comment]
我们已经更新了Huggingface Transformers模型代码，目前可以使用Transformers模型在mac上使用cpu推理。
We have updated the model code of Huggingface Transformers, and inference through cpu on mac computers are available through transformers.
