### ISSUE TITLE
[Feature Request]: 支持 ONNXRuntime

### ISSUE THREAD

**Issue by cxzx150133** [OpenBMB/MiniCPM#61]
### Feature request  / 功能建议

仓库地址：https://github.com/microsoft/onnxruntime
官网：https://onnxruntime.ai/

这个格式我了解的也不是很深，但是从描述上来看微软想在机器学习领域搞一个类似 3D 界的 GLTF 格式，让大模型平台无关化，最直接的好处我能想到的大概就是能在客户端用浏览器直接跑大模型。

**Comment by zh-zheng** [comment]
如果你有使用ONNXRuntime的需求，你可以使用我们提供的llama-format模型按照Llama的方式进行转换，例如参考这个[仓库](https://github.com/microsoft/Llama-2-Onnx)。
If you need to use ONNXRuntime, you can use the llama-format models we provide and convert them according to Llama's approach. For example, you can refer to this [repository](https://github.com/microsoft/Llama-2-Onnx).

**Comment by cxzx150133** [comment]
> 如果你有使用ONNXRuntime的需求，你可以使用我们提供的llama-format模型按照Llama的方式进行转换，例如参考这个[仓库](https://github.com/microsoft/Llama-2-Onnx)。 If you need to use ONNXRuntime, you can use the llama-format models we provide and convert them according to Llama's approach. For example, you can refer to this [repository](https://github.com/microsoft/Llama-2-Onnx).

好的，我试试。
Thanks, I'll try.
