### ISSUE TITLE
[Bug]: 使用Xcode进行 iOS端本地部署报错

### ISSUE THREAD

**Issue by gengcong1991** [OpenBMB/MiniCPM#65]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

使用Xcode 编译提供的demo LLMFarm工程时报错
0  0x104c4b648  __assert_rtn + 72
1  0x104b73c5c  ld::Fixup::applyFixup(ld::Atom const*, ld::LayoutLinkedImage const&, unsigned char*) const + 8268
2  0x104c067d8  ___ZN2ld16LayoutExecutable27writeContentWithoutLinkEditENSt3__14spanIhLm18446744073709551615EEEy_block_invoke + 332
3  0x18b1b9950  _dispatch_client_callout2 + 20
4  0x18b1ce1a4  _dispatch_apply_invoke_and_wait + 176
5  0x18b1cd464  _dispatch_apply_with_attr_f + 1176
6  0x18b1cd650  dispatch_apply + 96
7  0x104c069e4  void mapReduce<ld::Atom const*, mach_o::Error>(std::__1::span<ld::Atom const*, 18446744073709551615ul>, unsigned long, void (unsigned long, mach_o::Error&, std::__1::span<ld::Atom const*, 18446744073709551615ul>) block_pointer, void (std::__1::span<mach_o::Error, 18446744073709551615ul>) block_pointer) + 336
8  0x104c06594  ld::LayoutExecutable::writeContentWithoutLinkEdit(std::__1::span<unsigned char, 18446744073709551615ul>, unsigned long long) + 1180
9  0x104c0c020  ld::LayoutExecutable::writeToFile(char const*) + 15248
10  0x104bbe2e8  main + 9424
ld: Assertion failed: (extras.otherInstrOffset != 0 && "Kind::arm64_adrp_ldr missing extra info"), function applyFixup, file Fixup.cpp, line 793.
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### To Reproduce / 如何复现

clone项目后按照步骤进行编译

### Expected behavior / 期望的结果

能够正常编译

### Screenshots / 截图

![image](https://github.com/OpenBMB/MiniCPM/assets/29472831/30303ad9-096a-4e66-9e07-941d650bf459)

### Environment / 环境

```shell
-macOS 14.0
-M1pro 芯片 
-Xcode15.0
```

**Comment by zkh2016** [comment]
方便升级下xcode再重新编译试试吗？我这边在xcode15.2上编译正常。

**Comment by gengcong1991** [comment]
> 方便升级下xcode再重新编译试试吗？我这边在xcode15.2上编译正常。

升级 Xcode 15.2正常了 谢谢

**Comment by gengcong1991** [comment]
升级 Xcode 15.2正常了

**Comment by gengcong1991** [comment]
升级 Xcode 15.2正常了，问题关闭
