### ISSUE TITLE
[Bug]: Why is there such a huge discrepancy between the results obtained from running the command line and the output from the web demo?

### ISSUE THREAD

**Issue by LiangYong1216** [OpenBMB/MiniCPM#67]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

同样的问题，命令行输出的比较完整，但是web demo输出很差，这是为什么？
例如下面是命令行的输出：
请输入要查询的问题:
我想去北京旅游三天，请给我一个三天的攻略
当然可以！以下是为您设计的北京三天旅游攻略。

第一天：
1. 上午：故宫博物院（约2小时）
   故宫博物院是中国最大的古代宫殿建筑群，也是世界著名的博物馆。在这里您可以欣赏到丰富的文物和历史遗迹，了解中国古代宫廷文化。

2. 下午：天安门广场（约1小时）
   天安门广场是中国的象征，您可以在这里参观毛主席纪念堂、人民英雄纪念碑等景点，感受中国历史的厚重感。

3. 晚上：王府井步行街（约2小时）
   王府井步行街是北京最繁华的商业区之一，您可以品尝当地美食、购买纪念品，体验北京的购物氛围。

第二天：
1. 上午：颐和园（约3小时）
   颐和园是中国著名的皇家园林，以湖光山色著称。您可以在这里漫步、赏景，感受皇家园林的宁静与美丽。

2. 下午：圆明园遗址公园（约2小时）
   圆明园曾是清朝皇家园林，现已成为遗址公园。在这里您可以了解到中国园林艺术的辉煌历史，同时也可以参观一些遗址，感受历史的沧桑。

3. 晚上：南锣鼓巷（约2小时）
   南锣鼓巷是北京最具特色的胡同文化街区，您可以品尝地道的北京小吃，感受胡同生活的悠闲与惬意。

第三天：
1. 上午：长城（约4小时）
   长城是中国古代伟大的防御工程，您可以选择八达岭或慕田峪等著名景区游览。在长城上徒步，感受中国古代军事防御的宏伟与壮观。

2. 下午：天坛公园（约2小时）
   天坛公园是明清两朝皇帝祭天祈谷的场所，您可以在这里领略中国古代宗教建筑的独特魅力。

3. 晚上：北京夜景（约1小时）
   在夜幕降临后，您可以欣赏北京城市夜景，感受这座古老与现代交融的现代化大都市的魅力。

以上是一个为您设计的北京三天旅游攻略，希望您在旅途中度过愉快的时光。祝您旅途愉快！

web端的输出：
我想去北京旅游三天，请给我一个三天的攻略
当然可以。以下是一个适合在北京旅行的3天行程：
第一天：故宫博物院、天安门广场和长安街
早上：从酒店出发前往故宫博物院（约1小时车程）参观中国历史和文化博物馆的壮丽建筑以及珍贵的文物收藏品。建议提前在线购买门票以避免排队等候时间过长。在离开故宫之前，可以在附近的午门小吃摊品尝一些当地美食。下午：乘坐地铁或公交车到天安门广场游览毛主席纪念堂和国家大剧院等标志性建筑物；然后沿着长安街步行至王府井步行街购物区逛一逛并尝试当地的特色小吃如煎饼果子和豆汁儿。晚上：回到酒店休息后可以去附近的簋街夜市体验夜生活氛围，品味各种地道的小吃和其他娱乐活动。
完了，就结束了？这是为什么？

### To Reproduce / 如何复现

在命令行和web端输入相同的问题

### Expected behavior / 期望的结果

web端输出结果被截断了

### Screenshots / 截图

![image](https://github.com/OpenBMB/MiniCPM/assets/66230782/9fad8ca2-e713-46f7-a35b-99d78e00a5b0)

### Environment / 环境

```shell
- OS: [e.g. Ubuntu 16.04]
- Pytorch: [e.g. torch 2.1.0]
- CUDA: [e.g. CUDA 11.2]
- Device: [e.g. p100]
```

**Comment by SUDA-HLT-ywfang** [comment]
命令行推理是用的vllm吗？

**Comment by LiangYong1216** [comment]
命令行是这样的：
![image](https://github.com/OpenBMB/MiniCPM/assets/66230782/d7ec956b-64d6-454b-8683-a87541ab9366)

**Comment by SUDA-HLT-ywfang** [comment]
解码超参有一定影响，可以在demo界面上调整参数后，再试试
<img width="1529" alt="image" src="https://github.com/OpenBMB/MiniCPM/assets/47963924/424f2f1b-6b03-41c1-af88-a49be5ebf04d">

**Comment by LiangYong1216** [comment]
啊哈，我试试嗷
