### ISSUE TITLE
[Feature Request]: Base模型没有开源吗？

### ISSUE THREAD

**Issue by DumoeDss** [OpenBMB/MiniCPM#7]
### Feature request  / 功能建议

如题，请问只能在sft或者dpo模型上进行微调吗？

**Comment by ShengdingHu** [comment]
base模型会在后续随所有中间checkpoint一起开源，需要一定时间准备，敬请期待～
The base model will be open-sourced in the future along with all intermediate checkpoints. It requires some time to prepare, so please look forward to it～

**Comment by ShengdingHu** [comment]
We have opensourced the intermediate checkpoints! check [here](https://huggingface.co/openbmb/MiniCPM-2B-history)
