### ISSUE TITLE
[Feature Request]: 多模态版本的模型（minicpm-v）现在只有Android版本的，可以提供 iOS 版本么

### ISSUE THREAD

**Issue by xtxwy** [OpenBMB/MiniCPM#74]
### Feature request  / 功能建议

T.D.

**Comment by THUCSTHanxu13** [comment]
多模态版本输入图片需要开操作系统权限，安卓比较好搞，ios基本需要发一个app上商店了，所以当时没搞。后面我们推进下ios的开发。

**Comment by jctime** [comment]
ios版本需要一个app store 的账号，上线限制较多，由于我们主要开源的是模型，ios demo鼓励大家自主研发，我们暂时无法提供官方版本。

**Comment by zhjygit** [comment]
按照教程里面的方法在安卓手机部署，初始化报错，有成功的朋友吗？这个对安卓手机有硬性要求还是差不多都可以。
