### ISSUE TITLE
[Bug]: Convert_weight

### ISSUE THREAD

**Issue by Vinaysukhesh98** [OpenBMB/MiniCPM#80]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

.local/lib/python3.10/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm.error.InternalError: Traceback (most recent call last):
  10: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::runtime::Module (tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target)>::AssignTypedLambda<tvm::__mk_TVM23::{lambda(tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target)#1}>(tvm::__mk_TVM23::{lambda(tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::TVMRetValue)
  9: tvm::TIRToRuntime(tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target const&)
  8: tvm::codegen::Build(tvm::IRModule, tvm::Target)
  7: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::runtime::Module (tvm::IRModule, tvm::Target)>::AssignTypedLambda<tvm::codegen::__mk_TVM0::{lambda(tvm::IRModule, tvm::Target)#1}>(tvm::codegen::__mk_TVM0::{lambda(tvm::IRModule, tvm::Target)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::TVMRetValue)
  6: tvm::codegen::BuildSPIRV(tvm::IRModule, tvm::Target)
  5: tvm::codegen::LowerToSPIRV[abi:cxx11](tvm::IRModule, tvm::Target)
  4: tvm::codegen::CodeGenSPIRV::BuildFunction(tvm::tir::PrimFunc const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  3: tvm::codegen::spirv::IRBuilder::GetSType(tvm::runtime::DataType const&, unsigned int, unsigned int)
  2: tvm::codegen::spirv::IRBuilder::DeclareType(tvm::runtime::DataType const&, unsigned int, unsigned int)
  1: tvm::codegen::spirv::IRBuilder::AddCapabilityFor(tvm::runtime::DataType const&)
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/target/spirv/ir_builder.cc", line 566
InternalError: Check failed: (spirv_support_.supports_float16) is false: Vulkan target does not support Float16 capability.  If your device supports 16-bit float operations, please either add -supports_float16=1 to the target, or query all device parameters by adding -from_device=0.

### To Reproduce / 如何复现

cloned https://github.com/OpenBMB/mlc-MiniCPM.git
mkdir -p build && cd build
# generate build configuration
python3 ../cmake/gen_cmake_config.py && cd ..
# build `mlc_chat_cli`
cd build && cmake .. && cmake --build . --parallel $(nproc) && cd ..
# install
cd python && pip install -e . && cd ..

### Environment / 环境

```shell
- OS: [e.g. Ubuntu 20.04]-ubuntu-22
- Pytorch: [e.g. torch 2.0.0]
- CUDA: [e.g. CUDA 11.8]-no
- Device: [e.g. A10, RTX3090]
ml-dtypes                0.3.2
mlc-ai-nightly           0.15.1
mlc-ai-nightly-cu117     0.12.dev2149
mlc-chat                 0.1.dev0       mlc-MiniCPM/python
torch                    2.1.2
```

**Comment by Vinaysukhesh98** [comment]
could able to compile with float 32 dtype
mlc-MiniCPM/python/mlc_chat/interface/gen_config.py", line 149, in gen_config
    fast_tokenizer.backend_tokenizer.save(str(tokenizer_json_save_dest))

**Comment by Achazwl** [comment]
mlc-MiniCPM is only tested on Android. I notice that you are on a Linux device.
On PC devices, we recommend using llama.cpp.
We thanks [@runfuture](https://github.com/runfuture) for supporting MiniCPM into [llama.cpp](https://github.com/ggerganov/llama.cpp), and we can now use llama.cpp to run gguf format MiniCPM.

**Comment by Vinaysukhesh98** [comment]
> If you need to compile to Android device, select OpenCL instead of Vulkan when preparing your mlc package

i have recopiled mlc pacakage with open cl still getting same error , do i need to recompile the tvm?

**Comment by Achazwl** [comment]
OpenCL should support float16, what's the new error message

**Comment by Vinaysukhesh98** [comment]
argument --model-type: invalid choice: 'minicpm_v' (choose from 'auto', 'llama', 'mistral', 'gemma', 'gpt2', 'mixtral', 'gpt_neox', 'gpt_bigcode', 'phi-msft', 'phi', 'qwen', 'qwen2', 'stablelm', 'baichuan', 'internlm', 'rwkv5')

**Comment by Achazwl** [comment]
seems mlc-MiniCPM is not correctly installed. Are [these](https://github.com/OpenBMB/mlc-MiniCPM?tab=readme-ov-file#prepare-enviroment) done?

**Comment by Achazwl** [comment]
```bash
python3 ../cmake/gen_cmake_config.py && cd ..
cd build && cmake .. && cmake --build . --parallel $(nproc) && cd ..
cd python && pip install -e . && cd ..
```

these commands should be run in MLC-MiniCPM repo but not the original MLC-LLM repo

**Comment by Vinaysukhesh98** [comment]
yeah i have did the same

**Comment by Achazwl** [comment]
tvm is included in the 3rd, only setting the PATH env is enough.
You can paste your errors here.

**Comment by Vinaysukhesh98** [comment]
getting same error 
mlc_chat convert_weight --model-type ${MODEL_TYPE} ./dist/models/${MODEL_NAME}/ --quantization $QUANTIZATION -o dist/$MODEL_NAME/
------------------------- Usage -------------------------
usage: MLC AutoLLM Quantization Framework [-h] --quantization
                                          {q0f16,q0f32,q3f16_0,q3f16_1,q4f16_0,q4f16_1,q4f32_1,q4f16_2,q4f16_autoawq,q4f16_ft}
                                          [--model-type {auto,llama,mistral,gemma,gpt2,mixtral,gpt_neox,gpt_bigcode,phi-msft,phi,qwen,qwen2,stablelm,baichuan,internlm,rwkv5}]
                                          [--device DEVICE] [--source SOURCE]
                                          [--source-format {auto,huggingface-torch,huggingface-safetensor,awq}]
                                          --output OUTPUT
                                          config

positional arguments:
  config                1) Path to a HuggingFace model directory that contains
                        a `config.json` or 2) Path to `config.json` in
                        HuggingFace format, or 3) The name of a pre-defined
                        model architecture. A `config.json` file in
                        HuggingFace format defines the model architecture,
                        including the vocabulary size, the number of layers,
                        the hidden size, number of attention heads, etc.
                        Example: https://huggingface.co/codellama/CodeLlama-
                        7b-hf/blob/main/config.json. A HuggingFace directory
                        often contains a `config.json` which defines the model
                        architecture, the non-quantized model weights in
                        PyTorch or SafeTensor format, tokenizer
                        configurations, as well as an optional
                        `generation_config.json` provides additional default
                        configuration for text generation. Example: https://hu
                        ggingface.co/codellama/CodeLlama-7b-hf/tree/main.
                        (required)

options:
  -h, --help            show this help message and exit
  --quantization {q0f16,q0f32,q3f16_0,q3f16_1,q4f16_0,q4f16_1,q4f32_1,q4f16_2,q4f16_autoawq,q4f16_ft}
                        The quantization mode we use to compile. If
                        unprovided, will infer from `model`. (required,
                        choices: q0f16, q0f32, q3f16_0, q3f16_1, q4f16_0,
                        q4f16_1, q4f32_1, q4f16_2, q4f16_autoawq, q4f16_ft)
  --model-type {auto,llama,mistral,gemma,gpt2,mixtral,gpt_neox,gpt_bigcode,phi-msft,phi,qwen,qwen2,stablelm,baichuan,internlm,rwkv5}
                        Model architecture such as "llama". If not set, it is
                        inferred from `mlc-chat-config.json`. (default:
                        "auto")
  --device DEVICE       The device used to do quantization such as "cuda" or
                        "cuda:0". Will detect from local available GPUs if not
                        specified. (default: "auto")
  --source SOURCE       The path to original model weight, infer from `config`
                        if missing. (default: "auto")
  --source-format {auto,huggingface-torch,huggingface-safetensor,awq}
                        The format of source model weight, infer from `config`
                        if missing. (default: "auto", choices: auto,
                        huggingface-torch, huggingface-safetensor, awq")
  --output OUTPUT, -o OUTPUT
                        The output directory to save the quantized model
                        weight. Will create `params_shard_*.bin` and `ndarray-
                        cache.json` in this directory. (required)
------------------------- Error -------------------------
argument --model-type: invalid choice: 'minicpm_v' (choose from 'auto', 'llama', 'mistral', 'gemma', 'gpt2', 'mixtral', 'gpt_neox', 'gpt_bigcode', 'phi-msft', 'phi', 'qwen', 'qwen2', 'stablelm', 'baichuan', 'internlm', 'rwkv5')
 
model type notfound.

**Comment by Achazwl** [comment]
What's the error when you run the following commands under the MLC-MiniCPM folder

```
python3 ../cmake/gen_cmake_config.py && cd ..
cd build && cmake .. && cmake --build . --parallel $(nproc) && cd ..
cd python && pip install -e . && cd ..
```

I guess you have MLC-LLM version mlc-chat installed first and the MLC-MiniCPM version mlc-chat is not successfully installed, so that when you use mlc-chat to convert weight, python finds the MLC-LLM version. Try uninstall mlc-chat first.

**Comment by Vinaysukhesh98** [comment]
hi after re installing the setup am still getting same error
how can i resolve it.

**Comment by Vinaysukhesh98** [comment]
i have installed opencl libraries and build enabling opencl only still the device detectting vulkan , even i removed all vulkan drives what could be the possible issue.

**Comment by Achazwl** [comment]
May related to MLC-LLM (https://github.com/mlc-ai/mlc-llm/issues/1606). I cannot reproduce here.
