### ISSUE TITLE
dpo数据是直接用的ultrafeedback-binarized吗？中文模型能用吗？

### ISSUE THREAD

**Issue by no-execution** [OpenBMB/MiniCPM#81]
因为现在开源社区缺少比较优质的中文rlhf数据集，所以好奇已经放出来的ultrafeedback数据能不能直接用来dpo训练中文chat模型

**Comment by THUCSTHanxu13** [comment]
基础模型本身有一些跨语言的知识迁移能力，你用ultrafeedback做rlhf搞出来的模型中文能受益。但最好的方式还是针对性的做中文数据集进行rlhf

**Comment by xxlxms** [comment]
官方dpo模型使用的数据是啥呢？
