### ISSUE TITLE
tech-report 疑问

### ISSUE THREAD

**Issue by ericxsun** [OpenBMB/MiniCPM#85]
### Description / 描述

 tech report 有这个实验，

<img width="748" alt="WeChatWorkScreenshot_30a13bbd-4952-4145-aac4-60a572f6bab0" src="https://github.com/OpenBMB/MiniCPM/assets/1772912/0344a830-6f76-49a8-851c-019af72874a7">

那有对比过这样的效果吗

A0 预训练数据退火
B0 预训练数据+SFT数据退火

A1 预训练数据退火 + 4B sft
B1 预训练数据+SFT数据退火 -> 4B sft

**Comment by LDLINGLINGLING** [comment]
我们博客中的实验是您所述的第二种实验，
对于您第一种实验：
A0 预训练数据退火
B0 预训练数据+SFT数据退火
这种情况我个人感觉意义不大，因为模型最终总要进行sft，不进行sft就靠以上阶段应该是不可用的。
