### ISSUE TITLE
[Bug]: 安卓手机部署，convert_weight 报错 ValueError

### ISSUE THREAD

**Issue by zjloong** [OpenBMB/MiniCPM#86]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

Traceback (most recent call last):
  File "/Users/zhujinlong/miniconda3/envs/mini-cpm-env/bin/mlc_chat", line 33, in <module>
    sys.exit(load_entry_point('mlc-chat', 'console_scripts', 'mlc_chat')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhujinlong/Develop/Project/LLM/mlc-MiniCPM/python/mlc_chat/__main__.py", line 28, in main
    cli.main(sys.argv[2:])
  File "/Users/zhujinlong/Develop/Project/LLM/mlc-MiniCPM/python/mlc_chat/cli/convert_weight.py", line 87, in main
    convert_weight(
  File "/Users/zhujinlong/Develop/Project/LLM/mlc-MiniCPM/python/mlc_chat/interface/convert_weight.py", line 156, in convert_weight
    _convert_args(args)
  File "/Users/zhujinlong/Develop/Project/LLM/mlc-MiniCPM/python/mlc_chat/interface/convert_weight.py", line 107, in _convert_args
    for name, param in LOADER[args.source_format](
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhujinlong/Develop/Project/LLM/mlc-MiniCPM/python/mlc_chat/loader/huggingface_loader.py", line 97, in __init__
    check_parameter_usage(extern_param_map, set(self.torch_to_path.keys()))
  File "/Users/zhujinlong/Develop/Project/LLM/mlc-MiniCPM/python/mlc_chat/loader/utils.py", line 32, in check_parameter_usage
    raise ValueError(
ValueError: The following extern parameters do not exist in the weight files:
  model.layers.0.mlp.down_proj.weight
  model.layers.0.mlp.gate_proj.weight
  model.layers.0.mlp.up_proj.weight
  model.layers.0.self_attn.k_proj.weight
  model.layers.0.self_attn.o_proj.weight
  model.layers.0.self_attn.q_proj.weight
  model.layers.0.self_attn.v_proj.weight
  model.layers.1.mlp.down_proj.weight
  model.layers.1.mlp.gate_proj.weight
  model.layers.1.mlp.up_proj.weight
  model.layers.1.self_attn.k_proj.weight
  model.layers.1.self_attn.o_proj.weight
  model.layers.1.self_attn.q_proj.weight
  model.layers.1.self_attn.v_proj.weight
  model.layers.10.mlp.down_proj.weight
  model.layers.10.mlp.gate_proj.weight
  model.layers.10.mlp.up_proj.weight
  model.layers.10.self_attn.k_proj.weight
  model.layers.10.self_attn.o_proj.weight
  model.layers.10.self_attn.q_proj.weight
  model.layers.10.self_attn.v_proj.weight
  model.layers.11.mlp.down_proj.weight
  model.layers.11.mlp.gate_proj.weight
  model.layers.11.mlp.up_proj.weight
  model.layers.11.self_attn.k_proj.weight
  model.layers.11.self_attn.o_proj.weight
  model.layers.11.self_attn.q_proj.weight
  model.layers.11.self_attn.v_proj.weight
  model.layers.12.mlp.down_proj.weight
  model.layers.12.mlp.gate_proj.weight
  model.layers.12.mlp.up_proj.weight
  model.layers.12.self_attn.k_proj.weight
  model.layers.12.self_attn.o_proj.weight
  model.layers.12.self_attn.q_proj.weight
  model.layers.12.self_attn.v_proj.weight
  model.layers.13.mlp.down_proj.weight
  model.layers.13.mlp.gate_proj.weight
  model.layers.13.mlp.up_proj.weight
  model.layers.13.self_attn.k_proj.weight
  model.layers.13.self_attn.o_proj.weight
  model.layers.13.self_attn.q_proj.weight
  model.layers.13.self_attn.v_proj.weight
  model.layers.14.mlp.down_proj.weight
  model.layers.14.mlp.gate_proj.weight
  model.layers.14.mlp.up_proj.weight
  model.layers.14.self_attn.k_proj.weight
  model.layers.14.self_attn.o_proj.weight
  model.layers.14.self_attn.q_proj.weight
  model.layers.14.self_attn.v_proj.weight
  model.layers.15.mlp.down_proj.weight
  model.layers.15.mlp.gate_proj.weight
  model.layers.15.mlp.up_proj.weight
  model.layers.15.self_attn.k_proj.weight
  model.layers.15.self_attn.o_proj.weight
  model.layers.15.self_attn.q_proj.weight
  model.layers.15.self_attn.v_proj.weight
  model.layers.16.mlp.down_proj.weight
  model.layers.16.mlp.gate_proj.weight
  model.layers.16.mlp.up_proj.weight
  model.layers.16.self_attn.k_proj.weight
  model.layers.16.self_attn.o_proj.weight
  model.layers.16.self_attn.q_proj.weight
  model.layers.16.self_attn.v_proj.weight
  model.layers.17.mlp.down_proj.weight
  model.layers.17.mlp.gate_proj.weight
  model.layers.17.mlp.up_proj.weight
  model.layers.17.self_attn.k_proj.weight
  model.layers.17.self_attn.o_proj.weight
  model.layers.17.self_attn.q_proj.weight
  model.layers.17.self_attn.v_proj.weight
  model.layers.18.mlp.down_proj.weight
  model.layers.18.mlp.gate_proj.weight
  model.layers.18.mlp.up_proj.weight
  model.layers.18.self_attn.k_proj.weight
  model.layers.18.self_attn.o_proj.weight
  model.layers.18.self_attn.q_proj.weight
  model.layers.18.self_attn.v_proj.weight
  model.layers.19.mlp.down_proj.weight
  model.layers.19.mlp.gate_proj.weight
  model.layers.19.mlp.up_proj.weight
  model.layers.19.self_attn.k_proj.weight
  model.layers.19.self_attn.o_proj.weight
  model.layers.19.self_attn.q_proj.weight
  model.layers.19.self_attn.v_proj.weight
  model.layers.2.mlp.down_proj.weight
  model.layers.2.mlp.gate_proj.weight
  model.layers.2.mlp.up_proj.weight
  model.layers.2.self_attn.k_proj.weight
  model.layers.2.self_attn.o_proj.weight
  model.layers.2.self_attn.q_proj.weight
  model.layers.2.self_attn.v_proj.weight
  model.layers.20.mlp.down_proj.weight
  model.layers.20.mlp.gate_proj.weight
  model.layers.20.mlp.up_proj.weight
  model.layers.20.self_attn.k_proj.weight
  model.layers.20.self_attn.o_proj.weight
  model.layers.20.self_attn.q_proj.weight
  model.layers.20.self_attn.v_proj.weight
  model.layers.21.mlp.down_proj.weight
  model.layers.21.mlp.gate_proj.weight
  model.layers.21.mlp.up_proj.weight
  model.layers.21.self_attn.k_proj.weight
  model.layers.21.self_attn.o_proj.weight
  model.layers.21.self_attn.q_proj.weight
  model.layers.21.self_attn.v_proj.weight
  model.layers.22.mlp.down_proj.weight
  model.layers.22.mlp.gate_proj.weight
  model.layers.22.mlp.up_proj.weight
  model.layers.22.self_attn.k_proj.weight
  model.layers.22.self_attn.o_proj.weight
  model.layers.22.self_attn.q_proj.weight
  model.layers.22.self_attn.v_proj.weight
  model.layers.23.mlp.down_proj.weight
  model.layers.23.mlp.gate_proj.weight
  model.layers.23.mlp.up_proj.weight
  model.layers.23.self_attn.k_proj.weight
  model.layers.23.self_attn.o_proj.weight
  model.layers.23.self_attn.q_proj.weight
  model.layers.23.self_attn.v_proj.weight
  model.layers.24.mlp.down_proj.weight
  model.layers.24.mlp.gate_proj.weight
  model.layers.24.mlp.up_proj.weight
  model.layers.24.self_attn.k_proj.weight
  model.layers.24.self_attn.o_proj.weight
  model.layers.24.self_attn.q_proj.weight
  model.layers.24.self_attn.v_proj.weight
  model.layers.25.mlp.down_proj.weight
  model.layers.25.mlp.gate_proj.weight
  model.layers.25.mlp.up_proj.weight
  model.layers.25.self_attn.k_proj.weight
  model.layers.25.self_attn.o_proj.weight
  model.layers.25.self_attn.q_proj.weight
  model.layers.25.self_attn.v_proj.weight
  model.layers.26.mlp.down_proj.weight
  model.layers.26.mlp.gate_proj.weight
  model.layers.26.mlp.up_proj.weight
  model.layers.26.self_attn.k_proj.weight
  model.layers.26.self_attn.o_proj.weight
  model.layers.26.self_attn.q_proj.weight
  model.layers.26.self_attn.v_proj.weight
  model.layers.27.mlp.down_proj.weight
  model.layers.27.mlp.gate_proj.weight
  model.layers.27.mlp.up_proj.weight
  model.layers.27.self_attn.k_proj.weight
  model.layers.27.self_attn.o_proj.weight
  model.layers.27.self_attn.q_proj.weight
  model.layers.27.self_attn.v_proj.weight
  model.layers.28.mlp.down_proj.weight
  model.layers.28.mlp.gate_proj.weight
  model.layers.28.mlp.up_proj.weight
  model.layers.28.self_attn.k_proj.weight
  model.layers.28.self_attn.o_proj.weight
  model.layers.28.self_attn.q_proj.weight
  model.layers.28.self_attn.v_proj.weight
  model.layers.29.mlp.down_proj.weight
  model.layers.29.mlp.gate_proj.weight
  model.layers.29.mlp.up_proj.weight
  model.layers.29.self_attn.k_proj.weight
  model.layers.29.self_attn.o_proj.weight
  model.layers.29.self_attn.q_proj.weight
  model.layers.29.self_attn.v_proj.weight
  model.layers.3.mlp.down_proj.weight
  model.layers.3.mlp.gate_proj.weight
  model.layers.3.mlp.up_proj.weight
  model.layers.3.self_attn.k_proj.weight
  model.layers.3.self_attn.o_proj.weight
  model.layers.3.self_attn.q_proj.weight
  model.layers.3.self_attn.v_proj.weight
  model.layers.30.mlp.down_proj.weight
  model.layers.30.mlp.gate_proj.weight
  model.layers.30.mlp.up_proj.weight
  model.layers.30.self_attn.k_proj.weight
  model.layers.30.self_attn.o_proj.weight
  model.layers.30.self_attn.q_proj.weight
  model.layers.30.self_attn.v_proj.weight
  model.layers.31.mlp.down_proj.weight
  model.layers.31.mlp.gate_proj.weight
  model.layers.31.mlp.up_proj.weight
  model.layers.31.self_attn.k_proj.weight
  model.layers.31.self_attn.o_proj.weight
  model.layers.31.self_attn.q_proj.weight
  model.layers.31.self_attn.v_proj.weight
  model.layers.32.mlp.down_proj.weight
  model.layers.32.mlp.gate_proj.weight
  model.layers.32.mlp.up_proj.weight
  model.layers.32.self_attn.k_proj.weight
  model.layers.32.self_attn.o_proj.weight
  model.layers.32.self_attn.q_proj.weight
  model.layers.32.self_attn.v_proj.weight
  model.layers.33.mlp.down_proj.weight
  model.layers.33.mlp.gate_proj.weight
  model.layers.33.mlp.up_proj.weight
  model.layers.33.self_attn.k_proj.weight
  model.layers.33.self_attn.o_proj.weight
  model.layers.33.self_attn.q_proj.weight
  model.layers.33.self_attn.v_proj.weight
  model.layers.34.mlp.down_proj.weight
  model.layers.34.mlp.gate_proj.weight
  model.layers.34.mlp.up_proj.weight
  model.layers.34.self_attn.k_proj.weight
  model.layers.34.self_attn.o_proj.weight
  model.layers.34.self_attn.q_proj.weight
  model.layers.34.self_attn.v_proj.weight
  model.layers.35.mlp.down_proj.weight
  model.layers.35.mlp.gate_proj.weight
  model.layers.35.mlp.up_proj.weight
  model.layers.35.self_attn.k_proj.weight
  model.layers.35.self_attn.o_proj.weight
  model.layers.35.self_attn.q_proj.weight
  model.layers.35.self_attn.v_proj.weight
  model.layers.36.mlp.down_proj.weight
  model.layers.36.mlp.gate_proj.weight
  model.layers.36.mlp.up_proj.weight
  model.layers.36.self_attn.k_proj.weight
  model.layers.36.self_attn.o_proj.weight
  model.layers.36.self_attn.q_proj.weight
  model.layers.36.self_attn.v_proj.weight
  model.layers.37.mlp.down_proj.weight
  model.layers.37.mlp.gate_proj.weight
  model.layers.37.mlp.up_proj.weight
  model.layers.37.self_attn.k_proj.weight
  model.layers.37.self_attn.o_proj.weight
  model.layers.37.self_attn.q_proj.weight
  model.layers.37.self_attn.v_proj.weight
  model.layers.38.mlp.down_proj.weight
  model.layers.38.mlp.gate_proj.weight
  model.layers.38.mlp.up_proj.weight
  model.layers.38.self_attn.k_proj.weight
  model.layers.38.self_attn.o_proj.weight
  model.layers.38.self_attn.q_proj.weight
  model.layers.38.self_attn.v_proj.weight
  model.layers.39.mlp.down_proj.weight
  model.layers.39.mlp.gate_proj.weight
  model.layers.39.mlp.up_proj.weight
  model.layers.39.self_attn.k_proj.weight
  model.layers.39.self_attn.o_proj.weight
  model.layers.39.self_attn.q_proj.weight
  model.layers.39.self_attn.v_proj.weight
  model.layers.4.mlp.down_proj.weight
  model.layers.4.mlp.gate_proj.weight
  model.layers.4.mlp.up_proj.weight
  model.layers.4.self_attn.k_proj.weight
  model.layers.4.self_attn.o_proj.weight
  model.layers.4.self_attn.q_proj.weight
  model.layers.4.self_attn.v_proj.weight
  model.layers.5.mlp.down_proj.weight
  model.layers.5.mlp.gate_proj.weight
  model.layers.5.mlp.up_proj.weight
  model.layers.5.self_attn.k_proj.weight
  model.layers.5.self_attn.o_proj.weight
  model.layers.5.self_attn.q_proj.weight
  model.layers.5.self_attn.v_proj.weight
  model.layers.6.mlp.down_proj.weight
  model.layers.6.mlp.gate_proj.weight
  model.layers.6.mlp.up_proj.weight
  model.layers.6.self_attn.k_proj.weight
  model.layers.6.self_attn.o_proj.weight
  model.layers.6.self_attn.q_proj.weight
  model.layers.6.self_attn.v_proj.weight
  model.layers.7.mlp.down_proj.weight
  model.layers.7.mlp.gate_proj.weight
  model.layers.7.mlp.up_proj.weight
  model.layers.7.self_attn.k_proj.weight
  model.layers.7.self_attn.o_proj.weight
  model.layers.7.self_attn.q_proj.weight
  model.layers.7.self_attn.v_proj.weight
  model.layers.8.mlp.down_proj.weight
  model.layers.8.mlp.gate_proj.weight
  model.layers.8.mlp.up_proj.weight
  model.layers.8.self_attn.k_proj.weight
  model.layers.8.self_attn.o_proj.weight
  model.layers.8.self_attn.q_proj.weight
  model.layers.8.self_attn.v_proj.weight
  model.layers.9.mlp.down_proj.weight
  model.layers.9.mlp.gate_proj.weight
  model.layers.9.mlp.up_proj.weight
  model.layers.9.self_attn.k_proj.weight
  model.layers.9.self_attn.o_proj.weight
  model.layers.9.self_attn.q_proj.weight
  model.layers.9.self_attn.v_proj.weight

### To Reproduce / 如何复现

mlc_chat convert_weight --model-type minicpm ./dist/models/MiniCPM-2B-sft-int4/ --quantization q4f16_1 -o dist/MiniCPM-2B-sft-int4/                                         

### Environment / 环境

```shell
- OS: [e.g. Ubuntu 20.04]
- Pytorch: [e.g. torch 2.0.0]
- CUDA: [e.g. CUDA 11.8]
- Device: [e.g. A10, RTX3090]
```

**Comment by Achazwl** [comment]
The int4 version in huggingface has model weight store in huggingface's GPTQ format, which is not compatible in mlc-MiniCPM. Use the float version directly.
