### ISSUE TITLE
hf上DPO的Int4量化版没看到

### ISSUE THREAD

**Issue by regedo** [OpenBMB/MiniCPM#87]
### Feature request  / 功能建议

![image](https://github.com/OpenBMB/MiniCPM/assets/24564951/18aecca1-42db-4760-9f31-ab51f205d065)

**Comment by zh-zheng** [comment]
之前误设置为了private，现在已经[公开](https://huggingface.co/openbmb/MiniCPM-2B-dpo-int4)。
It was mistakenly set as private before, and we have already made it [public](https://huggingface.co/openbmb/MiniCPM-2B-dpo-int4).
