### ISSUE TITLE
WSD学习率退火阶段结束后loss还在保持下降趋势

### ISSUE THREAD

**Issue by niyunsheng** [OpenBMB/MiniCPM#88]
感谢你们的工作，注意到你们提到的WSD优化器，退火阶段loss还在下降，并且下降趋势没有放缓。

这时候是否需要增加数据固定0.1 lr继续退火阶段，以达到更低的loss？

![](https://shengdinghu.notion.site/image/https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2F30c36155-a603-469f-957f-b0854b6e2372%2Fcc95e459-7aec-4f53-94a4-7aa80ee4fdfc%2FUntitled.png?table=block&id=69f8c645-1acc-4ec7-ad86-50dd577eb1a7&spaceId=30c36155-a603-469f-957f-b0854b6e2372&width=2000&userId=&cache=v2)

**Comment by niyunsheng** [comment]
退火阶段的学习率具体是线性，还是指数呢？如果是指数的话，T和N的关系是什么呢？
![](https://shengdinghu.notion.site/image/https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2F30c36155-a603-469f-957f-b0854b6e2372%2Ff70abacd-85ca-423c-b107-875cf6c96707%2FUntitled.png?table=block&id=ddb7a6fd-594e-4110-9e9a-491586d113f4&spaceId=30c36155-a603-469f-957f-b0854b6e2372&width=770&userId=&cache=v2)

**Comment by LDLINGLINGLING** [comment]
![image](https://github.com/OpenBMB/MiniCPM/assets/47373076/38e00fd7-40c6-418c-a803-802fdaae5f04)
以上文字来自于minicpm的官方技术博客，说明了退火阶段的学习率是指数衰减的。
