### ISSUE TITLE
[Bad Case]: colab示例无法使用GPU

### ISSUE THREAD

**Issue by LY1806620741** [OpenBMB/MiniCPM#89]
### Description / 描述

在 https://colab.research.google.com/drive/1tJcfPyWGWA5HezO7GKLeyeIso0HyOc0l?usp=sharing 中，使用GPU进行运算时，在计算回答会报FlashAttention only supports Ampere GPUs or newer. 错误

### Case Explaination / 案例解释

colab示例，非模型功能

**Comment by THUCSTHanxu13** [comment]
Flash attention只能在特定架构的GPUs跑，应该是colab里面的GPU型号太老了

**Comment by LY1806620741** [comment]
所以可以增加一些tips？或者使用其他示例
