### ISSUE TITLE
[Bad Case]: model doesn't load after converting from HF (fresh env)

### ISSUE THREAD

**Issue by abacaj** [OpenBMB/MiniCPM#9]
### Description / 描述

Followed instructions in: https://github.com/OpenBMB/MiniCPM/blob/main/README-en.md#quick-start

Failed at step > `python inference.py --model_path <vllmcpm_repo_path> --prompt_path prompts/prompt_final.txt`
Model is converted correctly but I get HF transformer error when running inference.py:

```
ValueError: The checkpoint you are trying to load has model type `cpm_dragonfly` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
```

Do I need to change my HF transformer version?

### Case Explaination / 案例解释

vllm version == 0.2.2
transformers version == 4.37.2

**Comment by ShengdingHu** [comment]
Thanks for pointing out! We will checkout whether it is indeed a requirement and add to requirements.txt
