### ISSUE TITLE
How to choose d_model 

### ISSUE THREAD

**Issue by JiwenJ** [OpenBMB/MiniCPM#94]
你好，我看到 d_model 设置为2304，请问一下这个数值是经验公式还是实验试出来的。

**Comment by THUCSTHanxu13** [comment]
一般先确定你想训练多大规模，目前来看，经验性的结论是，在同等参数规模下，d_model小层数多的模型训练稳定性会弱一点，但效果会更好一点，d_model和layer是一个需要balance的事情。

**Comment by THUCSTHanxu13** [comment]
传统2B规模的模型，层数采用32、36的比较多，我们想训练的深一点，定在了40层，相应地可以测算d_model

**Comment by JiwenJ** [comment]
appreciate that!
